local assets =
{
	Asset("ANIM", "anim/containers.zip"),
	Asset("ANIM", "anim/ceiling_lights.zip"),
    Asset("ANIM", "anim/interior_window.zip"),
    Asset("ANIM", "anim/interior_window_burlap.zip"),        
    Asset("ANIM", "anim/interior_wall_decals.zip"),    
    Asset("ANIM", "anim/interior_wall_decals_hoofspa.zip"),        
    Asset("ANIM", "anim/interior_window_lightfx.zip"),    
    Asset("ANIM", "anim/interior_wall_mirror.zip"),       
    Asset("ANIM", "anim/interior_floor_decor.zip"),        
    Asset("ANIM", "anim/interior_wall_decals_ruins.zip"), 
    Asset("ANIM", "anim/interior_wall_decals_florist.zip"),  
    Asset("ANIM", "anim/interior_wall_decals_deli.zip"),       
    Asset("ANIM", "anim/interior_wall_decals_batcave.zip"),  
    Asset("ANIM", "anim/interior_wall_decals_antiquities.zip"),
    Asset("ANIM", "anim/interior_wall_decals_antcave.zip"),    
    Asset("ANIM", "anim/interior_wall_decals_mayorsoffice.zip"),
    Asset("ANIM", "anim/interior_wall_decals_palace.zip"), 
    Asset("ANIM", "anim/interior_wallornament.zip"), 

    Asset("ANIM", "anim/room_shelves.zip"),   

    Asset("ANIM", "anim/window_mayorsoffice.zip"),
    Asset("ANIM", "anim/window_palace.zip"),    
    Asset("ANIM", "anim/window_palace_stainglass.zip"),        

    Asset("ANIM", "anim/interior_table.zip"),

    Asset("ANIM", "anim/window_tall_dome_build.zip"),
    Asset("ANIM", "anim/window_small_peaked_build.zip"),
    Asset("ANIM", "anim/window_large_square_build.zip"),

    Asset("ANIM", "anim/pig_ruins_well.zip"),      
    Asset("ANIM", "anim/ceiling_decor.zip"),     
    Asset("ANIM", "anim/light_dust_fx.zip"),

    Asset("ANIM", "anim/rugs.zip"),
    Asset("ANIM", "anim/interior_wall_decals_mayorsoffice.zip"),
    Asset("ANIM", "anim/interior_wall_decals_palace.zip"),  
}

local prefabs =
{
    "swinglightobject",
    "deco_roomglow",
}

return  MakePillarPlacer("deco_wood_cornerbeam_placer", "wall_decals", "interior_wall_decals", "3", {far = "4"}),
        MakePillarPlacer("deco_millinery_cornerbeam_placer", "wall_decals_millinery", "interior_wall_decals_millinery", "pillar_front", {far = "pillar_corner"}),
        MakePillarPlacer("deco_round_cornerbeam_placer", "wall_decals_accademia", "interior_wall_decals_accademia", "pillar_round_front", {far = "pillar_round_corner"}),
        MakePillarPlacer("deco_marble_cornerbeam_placer", "wall_decals_hoofspa", "interior_wall_decals_hoofspa", "pillar", {far = "pillar_corner"}),

        -- CHAIRS
        MakeFurniturePlacer("chair_classic_placer", "interior_chair", "interior_chair", "chair_classic"),
        MakeFurniturePlacer("chair_corner_placer", "interior_chair", "interior_chair", "chair_corner"),
        MakeFurniturePlacer("chair_bench_placer", "interior_chair", "interior_chair", "chair_bench"),
        MakeFurniturePlacer("chair_horned_placer", "interior_chair", "interior_chair", "chair_horned"),
        MakeFurniturePlacer("chair_footrest_placer", "interior_chair", "interior_chair", "chair_footrest"),
        MakeFurniturePlacer("chair_lounge_placer", "interior_chair", "interior_chair", "chair_lounge"),
        MakeFurniturePlacer("chair_massager_placer", "interior_chair", "interior_chair", "chair_massager"),
        MakeFurniturePlacer("chair_stuffed_placer", "interior_chair", "interior_chair", "chair_stuffed"),
        MakeFurniturePlacer("chair_rocking_placer", "interior_chair", "interior_chair", "chair_rocking"),
        MakeFurniturePlacer("chair_ottoman_placer", "interior_chair", "interior_chair", "chair_ottoman"),

        -- SHELVES
        MakeShelfPlacer("shelves_wood_placer",               "bookcase", "room_shelves", "wood"),
        MakeShelfPlacer("shelves_basic_placer",              "bookcase", "room_shelves", "basic"),
        MakeShelfPlacer("shelves_cinderblocks_placer",       "bookcase", "room_shelves", "cinderblocks"),
        MakeShelfPlacer("shelves_marble_placer",             "bookcase", "room_shelves", "marble"),
        MakeShelfPlacer("shelves_glass_placer",              "bookcase", "room_shelves", "glass"),
        MakeShelfPlacer("shelves_ladder_placer",             "bookcase", "room_shelves", "ladder"),
        MakeShelfPlacer("shelves_hutch_placer",              "bookcase", "room_shelves", "hutch"),
        MakeShelfPlacer("shelves_industrial_placer",         "bookcase", "room_shelves", "industrial"),
        MakeShelfPlacer("shelves_adjustable_placer",         "bookcase", "room_shelves", "adjustable"),
        MakeShelfPlacer("shelves_midcentury_placer",         "bookcase", "room_shelves", "midcentury"),
        MakeShelfPlacer("shelves_wallmount_placer",          "bookcase", "room_shelves", "wallmount"),
        MakeShelfPlacer("shelves_aframe_placer",             "bookcase", "room_shelves", "aframe"),
        MakeShelfPlacer("shelves_crates_placer",             "bookcase", "room_shelves", "crates"),
        MakeShelfPlacer("shelves_fridge_placer",             "bookcase", "room_shelves", "fridge"),
        MakeShelfPlacer("shelves_floating_placer",           "bookcase", "room_shelves", "floating"),
        MakeShelfPlacer("shelves_pipe_placer",               "bookcase", "room_shelves", "pipe"),
        MakeShelfPlacer("shelves_hattree_placer",            "bookcase", "room_shelves", "hattree"),
        MakeShelfPlacer("shelves_pallet_placer",             "bookcase", "room_shelves", "pallet"),

        -- HANGING LIGHTS
        MakeCeilingLight("swinging_light_basic_bulb_placer",         "ceiling_lights", "ceiling_lights", "light_basic_bulb"),
        MakeCeilingLight("swinging_light_floral_bloomer_placer",     "ceiling_lights", "ceiling_lights", "light_floral_bloomer"),
        MakeCeilingLight("swinging_light_basic_metal_placer",        "ceiling_lights", "ceiling_lights", "light_basic_metal"),
        MakeCeilingLight("swinging_light_chandalier_candles_placer", "ceiling_lights", "ceiling_lights", "light_chandelier_candles"),
        MakeCeilingLight("swinging_light_rope_1_placer",             "ceiling_lights", "ceiling_lights", "light_rope1"),
        MakeCeilingLight("swinging_light_rope_2_placer",             "ceiling_lights", "ceiling_lights", "light_rope2"),
        MakeCeilingLight("swinging_light_floral_bulb_placer",        "ceiling_lights", "ceiling_lights", "light_floral_bulb"),
        MakeCeilingLight("swinging_light_pendant_cherries_placer",   "ceiling_lights", "ceiling_lights", "light_pendant_cherries"),
        MakeCeilingLight("swinging_light_floral_scallop_placer",     "ceiling_lights", "ceiling_lights", "light_floral_scallop"),
        MakeCeilingLight("swinging_light_floral_bloomer_placer",     "ceiling_lights", "ceiling_lights", "light_floral_bloomer"),
        MakeCeilingLight("swinging_light_tophat_placer",             "ceiling_lights", "ceiling_lights", "light_tophat"),
        MakeCeilingLight("swinging_light_derby_placer",              "ceiling_lights", "ceiling_lights", "light_derby"),
  
        -- WINDOWS
        MakeWindowPlacer("window_round_curtains_nails_placer",       "interior_window", "interior_window", "day_loop"),
        MakeWindowPlacer("window_round_burlap_placer",               "interior_window_burlap", "interior_window_burlap", "day_loop"),
        MakeWindowPlacer("window_small_peaked_curtain_placer",       "interior_window", "interior_window_small", "day_loop", {nocurtain = true}),
        MakeWindowPlacer("window_small_peaked_placer",               "interior_window", "interior_window_small", "day_loop", {nocurtain = true}),
        MakeWindowPlacer("window_large_square_placer",               "interior_window_large", "interior_window_large", "day_loop", {nocurtain = true}),
        MakeWindowPlacer("window_tall_placer",                       "interior_window_tall", "interior_window_tall", "day_loop", {nocurtain = true}),
        MakeWindowPlacer("window_large_square_curtain_placer",       "interior_window_large", "interior_window_large", "day_loop"),
        MakeWindowPlacer("window_tall_curtain_placer",               "interior_window_tall", "interior_window_tall", "day_loop"),

        MakeWindowPlacer("window_greenhouse_placer",                  "interior_window_greenhouse", "interior_window_greenhouse_build", "day_loop", {distance = 5}),


        MakeFurniturePlacer("deco_lamp_fringe_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_fringe"),
        MakeFurniturePlacer("deco_lamp_stainglass_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_stainglass"),
        MakeFurniturePlacer("deco_lamp_downbridge_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_downbridge"),
        MakeFurniturePlacer("deco_lamp_2embroidered_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_2embroidered"),
        MakeFurniturePlacer("deco_lamp_ceramic_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_ceramic"),
        MakeFurniturePlacer("deco_lamp_glass_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_glass"),
        MakeFurniturePlacer("deco_lamp_2fringes_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_2fringes"),
        MakeFurniturePlacer("deco_lamp_candelabra_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_candelabra"),
        MakeFurniturePlacer("deco_lamp_elizabethan_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_elizabethan"),
        MakeFurniturePlacer("deco_lamp_gothic_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_gothic"),
        MakeFurniturePlacer("deco_lamp_orb_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_orb"),
        MakeFurniturePlacer("deco_lamp_bellshade_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_bellshade"),
        MakeFurniturePlacer("deco_lamp_crystals_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_crystals"),
        MakeFurniturePlacer("deco_lamp_upturn_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_upturn"),
        MakeFurniturePlacer("deco_lamp_2upturns_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_2upturns"),
        MakeFurniturePlacer("deco_lamp_spool_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_spool"),
        MakeFurniturePlacer("deco_lamp_edison_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_edison"),
        MakeFurniturePlacer("deco_lamp_adjustable_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_adjustable"),
        MakeFurniturePlacer("deco_lamp_rightangles_placer", "interior_floorlamp", "interior_floorlamp", "floorlamp_rightangles"),

        -- ROOM PROPS
        MakeFurniturePlacer("deco_chaise_placer", "interior_floor_decor", "interior_floor_decor", "chaise"),
        MakeFurniturePlacer("deco_lamp_hoofspa_placer", "interior_floor_decor", "interior_floor_decor", "lamp"),
        MakeFurniturePlacer("deco_plantholder_marble_placer", "interior_floor_decor", "interior_floor_decor", "plant"),
        MakeFurniturePlacer("deco_table_banker_placer", "interior_table", "interior_table", "table_banker"),
        MakeFurniturePlacer("deco_table_round_placer", "interior_table", "interior_table", "table_round"),
        MakeFurniturePlacer("deco_table_diy_placer", "interior_table", "interior_table", "table_diy"),
        MakeFurniturePlacer("deco_table_raw_placer", "interior_table", "interior_table", "table_raw"),
        MakeFurniturePlacer("deco_table_crate_placer", "interior_table", "interior_table", "table_crate"),
        MakeFurniturePlacer("deco_table_chess_placer", "interior_table", "interior_table", "table_chess"),

        -- RUGS
        MakeRugPlacer("rug_round_placer",              "rugs", "rugs", "rug_round",        {distance = 2}),
        MakeRugPlacer("rug_square_placer",             "rugs", "rugs", "rug_square",       {distance = 2}),
        MakeRugPlacer("rug_oval_placer",               "rugs", "rugs", "rug_oval",         {distance = 2.8}),
        MakeRugPlacer("rug_rectangle_placer",          "rugs", "rugs", "rug_rectangle",    {distance = 2.8}),
        MakeRugPlacer("rug_leather_placer",            "rugs", "rugs", "rug_leather",      {distance = 2.8}),
        MakeRugPlacer("rug_fur_placer",                "rugs", "rugs", "rug_fur",          {distance = 2.8}),
        MakeRugPlacer("rug_circle_placer",             "rugs", "rugs", "half_circle",      {distance = 2}),
        MakeRugPlacer("rug_hedgehog_placer",           "rugs", "rugs", "rug_hedgehog",     {distance = 2}),
        MakeRugPlacer("rug_porcupuss_placer",          "rugs", "rugs", "rug_porcupuss"),
        MakeRugPlacer("rug_hoofprint_placer",          "rugs", "rugs", "rug_hoofprints",   {distance = 2.8}), 
        MakeRugPlacer("rug_octagon_placer",            "rugs", "rugs", "rug_octagon",      {distance = 2.8}), 
        MakeRugPlacer("rug_swirl_placer",              "rugs", "rugs", "rug_swirl",        {distance = 2.8}), 
        MakeRugPlacer("rug_catcoon_placer",            "rugs", "rugs", "rug_catcoon",      {distance = 2.8}), 
        MakeRugPlacer("rug_rubbermat_placer",          "rugs", "rugs", "rug_rubbermat",    {distance = 2.8}), 
        MakeRugPlacer("rug_web_placer",                "rugs", "rugs", "rug_web",          {distance = 2.8}), 
        MakeRugPlacer("rug_metal_placer",              "rugs", "rugs", "rug_metal",        {distance = 2.8}), 
        MakeRugPlacer("rug_wormhole_placer",           "rugs", "rugs", "rug_wormhole",     {distance = 2.8}), 
        MakeRugPlacer("rug_braid_placer",              "rugs", "rugs", "rug_braid",        {distance = 2.8}), 
        MakeRugPlacer("rug_beard_placer",              "rugs", "rugs", "rug_beard",        {distance = 2.8}), 
        MakeRugPlacer("rug_nailbed_placer",            "rugs", "rugs", "rug_nailbed"), 
        MakeRugPlacer("rug_crime_placer",              "rugs", "rugs", "rug_crime",        {distance = 2.8}), 
        MakeRugPlacer("rug_tiles_placer",              "rugs", "rugs", "rug_tiles",        {distance = 2.8}), 

        -- PLANTHOLDERS
        MakeFurniturePlacer("deco_plantholder_basic_placer",          "interior_plant", "interior_plant", "plant_basic"),
        MakeFurniturePlacer("deco_plantholder_wip_placer",            "interior_plant", "interior_plant", "plant_wip"),
        MakeFurniturePlacer("deco_plantholder_fancy_placer",          "interior_plant", "interior_plant", "plant_fancy"),
        MakeFurniturePlacer("deco_plantholder_bonsai_placer",         "interior_plant", "interior_plant", "plant_bonsai"),
        MakeFurniturePlacer("deco_plantholder_dishgarden_placer",     "interior_plant", "interior_plant", "plant_dishgarden"),
        MakeFurniturePlacer("deco_plantholder_philodendron_placer",   "interior_plant", "interior_plant", "plant_philodendron"),
        MakeFurniturePlacer("deco_plantholder_orchid_placer",         "interior_plant", "interior_plant", "plant_orchid"),
        MakeFurniturePlacer("deco_plantholder_draceana_placer",       "interior_plant", "interior_plant", "plant_draceana"),
        MakeFurniturePlacer("deco_plantholder_xerographica_placer",   "interior_plant", "interior_plant", "plant_xerographica"),
        MakeFurniturePlacer("deco_plantholder_birdcage_placer",       "interior_plant", "interior_plant", "plant_birdcage"),
        MakeFurniturePlacer("deco_plantholder_palm_placer",           "interior_plant", "interior_plant", "plant_palm"),
        MakeFurniturePlacer("deco_plantholder_zz_placer",             "interior_plant", "interior_plant", "plant_zz"),
        MakeFurniturePlacer("deco_plantholder_fernstand_placer",      "interior_plant", "interior_plant", "plant_fernstand"),
        MakeFurniturePlacer("deco_plantholder_fern_placer",           "interior_plant", "interior_plant", "plant_fern"),
        MakeFurniturePlacer("deco_plantholder_terrarium_placer",      "interior_plant", "interior_plant", "plant_terrarium"),
        MakeFurniturePlacer("deco_plantholder_plantpet_placer",       "interior_plant", "interior_plant", "plant_plantpet"),
        MakeFurniturePlacer("deco_plantholder_traps_placer",          "interior_plant", "interior_plant", "plant_traps"),
        MakeFurniturePlacer("deco_plantholder_pitchers_placer",       "interior_plant", "interior_plant", "plant_pitchers"),

        MakeFurniturePlacer("deco_plantholder_winterfeasttreeofsadness_placer",   "interior_plant", "interior_plant", "plant_winterfeasttreeofsadness"),
        MakeFurniturePlacer("deco_plantholder_winterfeasttree_placer",            "interior_floorlamp", "interior_floorlamp", "festivetree_idle"),

        -- WALL ORNAMENTS

        -- WALL DECO
        MakeWallDecoPlacer("deco_antiquities_wallfish_placer",             "interior_wallornament", "interior_wallornament", "fish"),
        MakeWallDecoPlacer("deco_antiquities_beefalo_placer",              "interior_wallornament", "interior_wallornament", "beefalo", {distance = 4}),
        MakeWallDecoPlacer("deco_wallornament_photo_placer",               "interior_wallornament", "interior_wallornament", "photo"),
        MakeWallDecoPlacer("deco_wallornament_fulllength_mirror_placer",   "interior_wallornament", "interior_wallornament", "fulllength_mirror"),
        MakeWallDecoPlacer("deco_wallornament_embroidery_hoop_placer",     "interior_wallornament", "interior_wallornament", "embroidery_hoop"),
        MakeWallDecoPlacer("deco_wallornament_mosaic_placer",              "interior_wallornament", "interior_wallornament", "mosaic"),
        MakeWallDecoPlacer("deco_wallornament_wreath_placer",              "interior_wallornament", "interior_wallornament", "wreath"),
        MakeWallDecoPlacer("deco_wallornament_axe_placer",                 "interior_wallornament", "interior_wallornament", "axe"),
        MakeWallDecoPlacer("deco_wallornament_hunt_placer",                "interior_wallornament", "interior_wallornament", "hunt", {distance = 4}),
        MakeWallDecoPlacer("deco_wallornament_periodic_table_placer",      "interior_wallornament", "interior_wallornament", "periodic_table", {distance = 4}),
        MakeWallDecoPlacer("deco_wallornament_gears_art_placer",           "interior_wallornament", "interior_wallornament", "gears_art"),
        MakeWallDecoPlacer("deco_wallornament_cape_placer",                "interior_wallornament", "interior_wallornament", "cape"),
        MakeWallDecoPlacer("deco_wallornament_no_smoking_placer",          "interior_wallornament", "interior_wallornament", "no_smoking"),
        MakeWallDecoPlacer("deco_wallornament_black_cat_placer",           "interior_wallornament", "interior_wallornament", "black_cat"),

        -- DOORS
        MakeDoorPlacer("wood_door_placer",    "player_house_doors", "player_house_doors", "wood_door_close_north"),
        MakeDoorPlacer("stone_door_placer",   "player_house_doors", "player_house_doors", "stone_door_close_north"),
        MakeDoorPlacer("organic_door_placer", "player_house_doors", "player_house_doors", "organic_door_close_north"),
        MakeDoorPlacer("iron_door_placer", 	 "player_house_doors", "player_house_doors", "iron_door_close_north"),
        MakeDoorPlacer("pillar_door_placer",  "player_house_doors", "player_house_doors", "pillar_door_close_north"),
        MakeDoorPlacer("curtain_door_placer", "player_house_doors", "player_house_doors", "curtain_door_close_north"),
        MakeDoorPlacer("round_door_placer", 	 "player_house_doors", "player_house_doors", "round_door_close_north"),
        MakeDoorPlacer("plate_door_placer", 	 "player_house_doors", "player_house_doors", "plate_door_close_north")