-- PORKLAND
STRINGS.NAMES.PIG_PALACE = "Palace"
STRINGS.NAMES.PIGMAN_QUEEN = "Pig Queen"
STRINGS.NAMES.PIG_SCEPTER = "Royal Scepter"
STRINGS.NAMES.PIGCROWNHAT = "Royal Crown"
STRINGS.NAMES.PIG_SHOP_FLORIST = "Miss Sow's\nFloral Arrangements"
STRINGS.NAMES.PIG_SHOP_GENERAL = "Pigg and Pigglet's\nGeneral Store"
STRINGS.NAMES.PIG_SHOP_HOOFSPA = "Curly Tails\nMud Spa"
STRINGS.NAMES.PIG_SHOP_PRODUCE = "Swinesbury Fine Grocer's"
STRINGS.NAMES.PIG_SHOP_ANTIQUITIES = "'The Sty' Oddities Emporium"
STRINGS.NAMES.PIG_SHOP_DELI = "The Sterling Trough Deli"
STRINGS.NAMES.PIG_SHOP_CITYHALL = "Swinesbury City Hall"
STRINGS.NAMES.PIG_SHOP_CITYHALL_PLAYER = "My City Hall"
STRINGS.NAMES.PIG_SHOP_BANK = "Swinesbury Mineral Exchange"

STRINGS.NAMES.PIG_SHOP_ARCANE = "The Flying Pig \nArcane Shop"
STRINGS.NAMES.PIG_SHOP_WEAPONS = "The Boar's Tusk \nWeapon Shop"
STRINGS.NAMES.PIG_SHOP_HATSHOP = "The Sow's Ear \nHat Shop"
STRINGS.NAMES.PIG_SHOP_ACADEMY = "Swinesbury Academy"
STRINGS.NAMES.PIG_SHOP_TINKER = "The Tinkerer's Tower"

STRINGS.NAMES.PIGMAN_BEAUTICIAN = "Beautician"
STRINGS.NAMES.PIGMAN_ROYALGUARD = "Royal Guard"
STRINGS.NAMES.PIGMAN_COLLECTOR = "Collector"
STRINGS.NAMES.PIGMAN_MAYOR = "Mayor Truffleston"
STRINGS.NAMES.PIGMAN_BANKER = "Banker"
STRINGS.NAMES.PIGMAN_MINER = "Miner"
STRINGS.NAMES.PIGMAN_MECHANIC = "Worker"
STRINGS.NAMES.PIGMAN_FARMER = "Farmer"
STRINGS.NAMES.PIGMAN_FLORIST = "Florist"
STRINGS.NAMES.PIGMAN_STOREOWNER = "Shopkeep"
STRINGS.NAMES.PIG_COIN = "Sty Piece"
STRINGS.NAMES.TREE_PILLAR = "Great Leafy Stalk"
STRINGS.NAMES.PIGHOUSE_CITY = "Town House"
STRINGS.NAMES.PIGHOUSE_FARM = "Farm House"
STRINGS.NAMES.PIGHOUSE_MINE = "Quarry Lodgings"
STRINGS.NAMES.PIG_GUARD_TOWER ="Watch Tower" 
STRINGS.NAMES.PIG_GUARD_TOWER_PALACE ="Watch Tower"
STRINGS.NAMES.CITY_LAMP = "Lamp Post"
STRINGS.NAMES.DUNGBEETLE = "Dung Beetle"
STRINGS.NAMES.DUNGBALL = "Dung Ball"
STRINGS.NAMES.DUNGPILE = "Dung Pile"
STRINGS.NAMES.PIGEON = "Pigeon"
STRINGS.NAMES.SPIDER_MONKEY = "Spider Monkey"
STRINGS.NAMES.SPIDER_MONKEY_TREE = "Cocooned Tree"
STRINGS.NAMES.BILL = "Platapine"
STRINGS.NAMES.TOPIARY = "Intricate Topiary"
STRINGS.NAMES.LAWNORNAMENT = "Lawn Decoration"
STRINGS.NAMES.HEDGE = "Hedge"
STRINGS.NAMES.RAINFORESTTREE = "Rainforest Tree"
STRINGS.NAMES.RAINFORESTTREE_ROT = "Sick Rainforest Tree"
STRINGS.NAMES.FLOWER_RAINFOREST = "Exotic Flower"
STRINGS.NAMES.HALBERD = "Halberd"
STRINGS.NAMES.CHICKEN = "Chicken"
STRINGS.NAMES.RUIN_GIANT_HEAD = "Massive Statue"
STRINGS.NAMES.RUINS_ARTICHOKE = "Old Statue"

STRINGS.NAMES.PIG_RUINS_ENTRANCE = "Ruinous Entrance"
STRINGS.NAMES.PIG_RUINS_EXIT = "Ruinous Entrance"
STRINGS.NAMES.PIG_RUINS_ENTRANCE2 = "Ruinous Entrance"
STRINGS.NAMES.PIG_RUINS_EXIT2 = "Ruinous Entrance"
STRINGS.NAMES.PIG_RUINS_ENTRANCE3 = "Ruinous Entrance"   

STRINGS.NAMES.PIG_RUINS_ENTRANCE4 = "Ruinous Entrance"
STRINGS.NAMES.PIG_RUINS_EXIT4 = "Ruinous Entrance"

STRINGS.NAMES.PIG_RUINS_ENTRANCE5 = "Ruinous Entrance"

STRINGS.NAMES.PIG_RUINS_ENTRANCE_SMALL = "Ruinous Entrance"

STRINGS.NAMES.GRASS_TALL = "Tall Grass"
STRINGS.NAMES.GLOWFLY = "Glowfly"
STRINGS.NAMES.GLOWFLY_COCOON = "Glowfly Cocoon"
STRINGS.NAMES.CHITIN = "Chitin"
STRINGS.NAMES.HANGING_VINE = "Hanging Vine"
STRINGS.NAMES.GRABBING_VINE = "Hanging Vine"
STRINGS.NAMES.VENUS_STALK = "Flytrap Stalk"
STRINGS.NAMES.WALKINGSTICK = "Stalking Stick"
STRINGS.NAMES.ADULT_FLYTRAP = "Snaptooth Flytrap"
STRINGS.NAMES.MEAN_FLYTRAP = "Snaptooth Seedling"
STRINGS.NAMES.SNAPDRAGON = "Snap Dragon"
STRINGS.NAMES.LILYPAD = "Giant Lily Pad"
STRINGS.NAMES.DEED = "Deed of Home Ownership"
STRINGS.NAMES.CONSTRUCTION_PERMIT = "Building Permit"
STRINGS.NAMES.DEMOLITION_PERMIT = "Demolition Permit"
STRINGS.NAMES.CONSTRUCTION_PERMIT = "House Expansion Permit"

STRINGS.NAMES.ZEB = "Zeb"
STRINGS.NAMES.SCORPION = "Scorpion"

STRINGS.NAMES.SHOP_SELLER = "Sell"
STRINGS.NAMES.SHOP_BUYER = "" -- THIS SHOULD BE BLANK

STRINGS.NAMES.PEAGAWK = "Peagawk"
STRINGS.NAMES.PEEKHEN = "Peep Hen"
STRINGS.NAMES.PEAGAWK_BUSH = "Blinkbush"
STRINGS.NAMES.PEAGAWKFEATHER = "Peagawk Plume"
STRINGS.NAMES.PEAGAWKFEATHER_PRISM = "Vibrant Peagawk Plume"
STRINGS.NAMES.PEAGAWKFEATHERHAT = "Peagawk Hat"

STRINGS.NAMES.ANTQUEEN = "Queen Womant"
STRINGS.NAMES.ANTMASKHAT = "Mant Mask"
STRINGS.NAMES.ANTSUIT = "Mant Suit"
STRINGS.NAMES.ANTHILL = "Mant Hill"
STRINGS.NAMES.ANTQUEEN_CHAMBERS = "Queen Womant Chambers"
STRINGS.NAMES.ANTQUEEN_THRONE = "Stalacmite Throne"
STRINGS.NAMES.ANTMAN_WARRIOR_EGG = "Mant Warrior Egg"

STRINGS.NAMES.ROCK_ANTCAVE = "Stalagmite"
STRINGS.NAMES.ANT_CAVE_LANTERN = "Lamp"

STRINGS.NAMES.GASMASKHAT = "Gas Mask"
STRINGS.NAMES.PITHHAT = "Pith Hat"

STRINGS.NAMES.PROP_DOOR = "Door"
STRINGS.NAMES.PHEROMONESTONE = "Pherostone"
STRINGS.NAMES.PIKO = "Piko"
STRINGS.NAMES.PIKO_ORANGE = "Orange Piko"

STRINGS.NAMES.RELIC_1 = "Lost Idol"
STRINGS.NAMES.RELIC_2 = "Lost Totem"
STRINGS.NAMES.RELIC_3 = "Relic Fragment"   
STRINGS.NAMES.RELIC_4 = "The Blue Sow"   
STRINGS.NAMES.RELIC_5 = "The Jeweled Truffle" 

STRINGS.NAMES.SHEARS = "Shears"
STRINGS.NAMES.MAGNIFYING_GLASS = "Magnifying Glass"

STRINGS.NAMES.VAMPIREBAT = "Vampire Bat"
STRINGS.NAMES.VAMPIREBATCAVE = "Cave Cleft"  
STRINGS.NAMES.LILYPAD = "Lily Pad"  
STRINGS.NAMES.LOTUS = "Lotus Plant" 
STRINGS.NAMES.REEDS_WATER = "Reeds"

STRINGS.NAMES.LOTUS_FLOWER ="Lotus Flower"
STRINGS.NAMES.LOTUS_FLOWER_COOKED ="Cooked Lotus Root"

STRINGS.NAMES.FROGLEGS_POISON = "Poison Dartfrog Legs"
STRINGS.NAMES.FROGLEGS_POISON_COOKED = "Cooked Dartfrog Legs"

STRINGS.NAMES.PIG_RUINS_TORCH_WALL = "Wall Brazier"
STRINGS.NAMES.PIG_RUINS_TORCH = "Crumbling Brazier"
STRINGS.NAMES.PIG_RUINS_HEAD = "Crumbling Visage"
STRINGS.NAMES.PIG_RUINS_ARTICHOKE = "Crumbling Carved Stone"
STRINGS.NAMES.PIG_RUINS_PIG = "Crumbling Icon"
STRINGS.NAMES.PIG_RUINS_IDOL = "Tempting Idol"
STRINGS.NAMES.PIG_RUINS_PLAQUE = "Eroding Totem"
STRINGS.NAMES.PIG_RUINS_MUSHROOM = "The Jeweled Truffle"
STRINGS.NAMES.PIG_RUINS_SOW = "The Blue Sow"

STRINGS.NAMES.PIG_RUINS_EXTRACTED = "Chiseled Stone"

STRINGS.NAMES.OINC = "Oinc"
STRINGS.NAMES.OINC_PL = "Oincs" -- the plural form of oinc
STRINGS.NAMES.OINC10 = "Tenpiece Oinc"
STRINGS.NAMES.OINC100 = "Centapiece Oinc"

STRINGS.NAMES.RABID_BEETLE = "Rabid Beetle"

STRINGS.NAMES.PARROT_BLUE = "Parrot"
STRINGS.NAMES.KINGFISHER = "Kingfisher"

STRINGS.NAMES.BURR = "Jungle Burr"   
STRINGS.NAMES.BURR_SAPLING = "Rainforest Tree Sapling"     

STRINGS.NAMES.DECO_RUINS_BEAM_ROOM = "Unimportant Pillar"
STRINGS.NAMES.DECO_RUINS_BEAM_ROOM_BLUE = "Unimportant Pillar"
STRINGS.NAMES.DECO_CAVE_BEAM_ROOM = "Unimportant Rock Pillar"
STRINGS.NAMES.DECO_CAVE_BAT_BURROW = "Spooky Hole"

STRINGS.NAMES.PIG_LATIN_1 = "Some strange pig scrawl"
STRINGS.NAMES.SMASHINGPOT = "A Smashing Pot"

STRINGS.NAMES.HIPPOPOTAMOOSE = "Hippopotamoose"

STRINGS.NAMES.PIGGHOST ="Ancient Spirit"

STRINGS.NAMES.GIANTGRUB = "Giant Grub"
STRINGS.NAMES.ANTCOMBHOME = "Antcomb Home"
STRINGS.NAMES.SECURITYCONTRACT = "Security Contract"

STRINGS.NAMES.TURF_PIGRUINS = "Ancient Stone Turf"
STRINGS.NAMES.TURF_RAINFOREST = "Rainforest Turf"
STRINGS.NAMES.TURF_DEEPRAINFOREST = "Dense Rainforest Turf"
STRINGS.NAMES.TURF_DEEPRAINFOREST_NOCANOPY = "Dense Turf"
STRINGS.NAMES.TURF_LAWN = "Lawn Turf"
STRINGS.NAMES.TURF_GASJUNGLE = "Toxic Turf"
STRINGS.NAMES.TURF_MOSS = "Mossy Turf"
STRINGS.NAMES.TURF_FIELDS = "Cultivated Turf"
STRINGS.NAMES.TURF_FOUNDATION = "Flat Stone Turf"
STRINGS.NAMES.TURF_COBBLEROAD = "Stone Road Turf" 

STRINGS.NAMES.PIG_SCEPTER = "Regal Scepter"
STRINGS.NAMES.HAT_PIGCROWN = "Regal Scepter"

STRINGS.NAMES.MANDRAKEMAN = "Elder Mandrake"
STRINGS.NAMES.MANDRAKEHOUSE = "Mandrake Hill"
STRINGS.NAMES.ANTMAN_WARRIOR = "Mant Warrior"
STRINGS.NAMES.ANTCHEST = "Honey Chest"

STRINGS.NAMES.BASEFAN = "Oscillating Fan"
STRINGS.NAMES.SPRINKLER = "Sprinkler"

-- HOME DECO ITEMS
STRINGS.NAMES.INTERIOR_FLOOR_MARBLE = "Marble Flooring"
STRINGS.NAMES.INTERIOR_FLOOR_CHECK = "Checkered Flooring"
STRINGS.NAMES.INTERIOR_FLOOR_PLAID_TILE = "Slate Flooring"
STRINGS.NAMES.INTERIOR_FLOOR_SHEET_METAL = "Sheet Metal Flooring"
STRINGS.NAMES.INTERIOR_FLOOR_WOOD = "Wood Flooring"

STRINGS.NAMES.INTERIOR_FLOOR_GARDENSTONE = "Garden Stone Flooring"
STRINGS.NAMES.INTERIOR_FLOOR_GEOMETRICTILES = "Geometric Tiles Flooring"
STRINGS.NAMES.INTERIOR_FLOOR_SHAG_CARPET = "Shag Carpet"
STRINGS.NAMES.INTERIOR_FLOOR_TRANSITIONAL = "Transitional Flooring"
STRINGS.NAMES.INTERIOR_FLOOR_WOODPANELS = "Wood Panel Flooring"
STRINGS.NAMES.INTERIOR_FLOOR_HERRINGBONE = "Herringbone Flooring"
STRINGS.NAMES.INTERIOR_FLOOR_HEXAGON = "Hexagon Flooring"
STRINGS.NAMES.INTERIOR_FLOOR_HOOF_CURVY = "Curcy Hoof Flooring"
STRINGS.NAMES.INTERIOR_FLOOR_OCTAGON = "Octagon Flooring"

STRINGS.NAMES.INTERIOR_WALL_WOOD = "Wood Paneling"
STRINGS.NAMES.INTERIOR_WALL_CHECKERED = "Checkered Wall Paper"
STRINGS.NAMES.INTERIOR_WALL_FLORAL = "Floral Wall Paper"
STRINGS.NAMES.INTERIOR_WALL_SUNFLOWER = "Sunflower Wall Paper"
STRINGS.NAMES.INTERIOR_WALL_HARLEQUIN = "Harlequin Wall Paper"   

STRINGS.NAMES.INTERIOR_WALL_PEAGAWK = "Peagawk Wall Paper"
STRINGS.NAMES.INTERIOR_WALL_PLAIN_DS = "Orange Wall Paper"
STRINGS.NAMES.INTERIOR_WALL_PLAIN_ROG = "Purple Wall Paper"
STRINGS.NAMES.INTERIOR_WALL_ROPE = "Rope Wall Panneling"
STRINGS.NAMES.INTERIOR_WALL_CIRCLES = "Circle Wall Tiling"
STRINGS.NAMES.INTERIOR_WALL_MARBLE = "Marble Wall Tiling"
STRINGS.NAMES.INTERIOR_WALL_MAYORSOFFICE = "Fine Wall Tiling"
STRINGS.NAMES.INTERIOR_WALL_FULLWALL_MOULDING = "Full Wall Moulding"
STRINGS.NAMES.INTERIOR_WALL_UPHOLSTERED = "Upholstered Wall"

STRINGS.NAMES.DECO_CHAISE = "Fancy Chaise"
STRINGS.NAMES.DECO_CHAIR_CLASSIC = "Classic Chair"
STRINGS.NAMES.DECO_CHAIR_CORNER = "Corner Chair"
STRINGS.NAMES.DECO_CHAIR_BENCH = "Bench"
STRINGS.NAMES.DECO_CHAIR_HORNED = "Horned Chair"
STRINGS.NAMES.DECO_CHAIR_FOOTREST = "Footrest"
STRINGS.NAMES.DECO_CHAIR_LOUNGE = "Lounge Chair"
STRINGS.NAMES.DECO_CHAIR_MASSAGER = "Massager Chair"
STRINGS.NAMES.DECO_CHAIR_STUFFED = "Stuffed Chair"
STRINGS.NAMES.DECO_CHAIR_ROCKING = "Rocking Chair"
STRINGS.NAMES.DECO_CHAIR_OTTOMAN = "Ottoman Chair"

STRINGS.NAMES.DECO_LAMP_FRINGE = "Fringe Lamp"
STRINGS.NAMES.DECO_LAMP_STAINGLASS = "Stainglass Lamp"
STRINGS.NAMES.DECO_LAMP_DOWNBRIDGE = "Downbridge Lamp"
STRINGS.NAMES.DECO_LAMP_2EMBROIDERED = "Dual Embroidered Lamp"
STRINGS.NAMES.DECO_LAMP_CERAMIC = "Ceramic Lamp"
STRINGS.NAMES.DECO_LAMP_GLASS = "Glass Lamp"
STRINGS.NAMES.DECO_LAMP_2FRINGES = "Dual Fringes Lamp"
STRINGS.NAMES.DECO_LAMP_CANDELABRA = "Candelabra Lamp"
STRINGS.NAMES.DECO_LAMP_ELIZABETHAN = "Elizabethan Lamp"
STRINGS.NAMES.DECO_LAMP_GOTHIC = "Gothic Lamp"
STRINGS.NAMES.DECO_LAMP_ORB = "Orb Lamp"
STRINGS.NAMES.DECO_LAMP_BELLSHADE = "Bellshade Lamp"
STRINGS.NAMES.DECO_LAMP_CRYSTALS = "Crystals Lamp"
STRINGS.NAMES.DECO_LAMP_UPTURN = "Upturn Lamp"
STRINGS.NAMES.DECO_LAMP_2UPTURNS = "Dual Upturn Lamp"
STRINGS.NAMES.DECO_LAMP_SPOOL = "Spool Lamp"
STRINGS.NAMES.DECO_LAMP_EDISON = "Edison Lamp"
STRINGS.NAMES.DECO_LAMP_ADJUSTABLE = "Adjustable Lamp"
STRINGS.NAMES.DECO_LAMP_RIGHTANGLES = "Right Angle Lamp"
STRINGS.NAMES.DECO_LAMP_HOOFSPA = "Fancy Lamp"

STRINGS.NAMES.DECO_PLANTHOLDER_BASIC = "Basic Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_WIP = "WIP Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_FANCY = "Fancy Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_BONSAI = "Bonsai Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_DISHGARDEN = "Dishgarden Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_PHILODENDRON = "Philodendron Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_ORCHID = "Orchid Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_DRACEANA = "Draceana Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_XEROGRAPHICA = "Xerographica Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_BIRDCAGE = "Birdcage Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_PALM = "Palm Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_ZZ = "ZZ Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_FERNSTAND = "Fernstand Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_FERN = "Fern Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_TERRARIUM = "Terrarium Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_PLANTPET = "Plantpet Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_TRAPS = "Traps Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_PITCHERS = "Pitcher Plantholder"
STRINGS.NAMES.DECO_PLANTHOLDER_MARBLE = "Marble Plantholder"

STRINGS.NAMES.DECO_PLANTHOLDER_WINTERFEASTTREEOFSADNESS = "\"Character\" Tree"  
STRINGS.NAMES.DECO_PLANTHOLDER_WINTERFEASTTREE = "Festive Tree."    

STRINGS.NAMES.DECO_TABLE_ROUND = "Round Table"
STRINGS.NAMES.DECO_TABLE_BANKER = "Hard Wood Desk"
STRINGS.NAMES.DECO_TABLE_DIY = "DIY Table"
STRINGS.NAMES.DECO_TABLE_RAW = "College Table"
STRINGS.NAMES.DECO_TABLE_CRATE = "Crate Table"
STRINGS.NAMES.DECO_TABLE_CHESS = "Chess Table"

STRINGS.NAMES.HOUSE_DOOR = "Simple Doorway"
STRINGS.NAMES.WOOD_DOOR = "Hardwood Door"
STRINGS.NAMES.STONE_DOOR = "Stone Archway"
STRINGS.NAMES.ORGANIC_DOOR = "Forest Door"
STRINGS.NAMES.IRON_DOOR = "Wrought Iron Door"
STRINGS.NAMES.PILLAR_DOOR = "Gothic Door"
STRINGS.NAMES.CURTAIN_DOOR = "Curtained Door"
STRINGS.NAMES.ROUND_DOOR = "Round Doorway"
STRINGS.NAMES.PLATE_DOOR = "Industrial Door"

STRINGS.NAMES.WINDOW_ROUND_CURTAINS_NAILS = "Round Window"
STRINGS.NAMES.WINDOW_ROUND_BURLAP = "Round Burlap Window"
STRINGS.NAMES.WINDOW_SMALL_PEAKED = "Peaked Window"
STRINGS.NAMES.WINDOW_LARGE_SQUARE = "Square Window"
STRINGS.NAMES.WINDOW_SMALL_PEAKED_CURTAIN = "Peaked Curtain Window"
STRINGS.NAMES.WINDOW_TALL = "Tall Window"
STRINGS.NAMES.WINDOW_LARGE_SQUARE_CURTAIN = "Large Square Curtain Window"
STRINGS.NAMES.WINDOW_TALL_CURTAIN = "Tall Curtain Window"
STRINGS.NAMES.WINDOW_GREENHOUSE = "Greenhouse Wall"
STRINGS.NAMES.WINDOW_ROUND = "Round Window"

STRINGS.NAMES.DECO_WOOD_BASE  = "Wooden Beam"
STRINGS.NAMES.DECO_WOOD       = "Planed Wood Column"
STRINGS.NAMES.DECO_MILLINERY  = "Millinery Column"
STRINGS.NAMES.DECO_ROUND      = "Round Column"
STRINGS.NAMES.DECO_MARBLE     = "Lit Marble Column"

STRINGS.NAMES.SWINGING_LIGHT_FLORAL_BLOOMER = "Floral Shade Hanging Light"
STRINGS.NAMES.SWINGING_LIGHT_CHANDALIER_CANDLES = "Chandelier"
STRINGS.NAMES.SWINGING_LIGHT_ROPE_1 = "Rope Light"
STRINGS.NAMES.SWINGING_LIGHT_FLORAL_BULB = "Blown Glass Bulb"
STRINGS.NAMES.SWINGING_LIGHT_PENDANT_CHERRIES = "Cherry Lamp Shade"
STRINGS.NAMES.SWINGING_LIGHT_BASIC_METAL = "Metal Shade Lamp"
STRINGS.NAMES.SWINGING_LIGHT_BASIC_BULB = "Wired Bulb"
STRINGS.NAMES.SWINGING_LIGHT_ROPE_2 = "Dual Rope Light"
STRINGS.NAMES.SWINGING_LIGHT_FLORAL_SCALLOP = "Hanging Blooming Lamp"
STRINGS.NAMES.SWINGING_LIGHT_FLORAL_BLOOMER = "Hanging Floral Lamp"
STRINGS.NAMES.SWINGING_LIGHT_TOPHAT = "Top Hat Light"
STRINGS.NAMES.SWINGING_LIGHT_DERBY = "Derby Light"

STRINGS.NAMES.DECO_WALLORNAMENT_PHOTO = "Photo"
STRINGS.NAMES.DECO_WALLORNAMENT_FULLLENGTH_MIRROR = "Full Length Mirror"
STRINGS.NAMES.DECO_WALLORNAMENT_EMBROIDERY_HOOP = "Embroidery Hoop"
STRINGS.NAMES.DECO_WALLORNAMENT_MOSAIC = "Mosaic"
STRINGS.NAMES.DECO_WALLORNAMENT_WREATH = "Wreath"
STRINGS.NAMES.DECO_WALLORNAMENT_AXE = "Axe"
STRINGS.NAMES.DECO_WALLORNAMENT_HUNT = "Hunt"
STRINGS.NAMES.DECO_WALLORNAMENT_PERIODIC_TABLE = "Periodic Table"
STRINGS.NAMES.DECO_WALLORNAMENT_GEARS_ART = "Gears Art"
STRINGS.NAMES.DECO_WALLORNAMENT_CAPE = "Cape"
STRINGS.NAMES.DECO_WALLORNAMENT_NO_SMOKING = "No Smoking"
STRINGS.NAMES.DECO_WALLORNAMENT_BLACK_CAT = "Black Cat"
STRINGS.NAMES.DECO_ANTIQUITIES_WALLFISH = "Tasteful Fish Mounting"
STRINGS.NAMES.DECO_ANTIQUITIES_BEEFALO = "Beefalo Mounting"

STRINGS.NAMES.RUG_ROUND = "Eye Rug"
STRINGS.NAMES.RUG_SQUARE = "Square Throw Rug"
STRINGS.NAMES.RUG_OVAL = "Oval Rug"
STRINGS.NAMES.RUG_RECTANGLE = "Large Rug"
STRINGS.NAMES.RUG_FUR = "Fur Throw Rug"
STRINGS.NAMES.RUG_HEDGEHOG = "Hedgehog Rug"
STRINGS.NAMES.RUG_PORCUPUSS = "Porcupus Hide"
STRINGS.NAMES.RUG_HOOFPRINT = "Hoofprint Rug"
STRINGS.NAMES.RUG_OCTAGON = "Octagon Rug"
STRINGS.NAMES.RUG_SWIRL = "Swirl Rug"
STRINGS.NAMES.RUG_CATCOON = "Catcoon Rug"
STRINGS.NAMES.RUG_RUBBERMAT = "Rubbermat Rug"
STRINGS.NAMES.RUG_WEB = "Web Rug"
STRINGS.NAMES.RUG_METAL = "Metal Rug"
STRINGS.NAMES.RUG_WORMHOLE = "Wormhole Rug"
STRINGS.NAMES.RUG_BRAID = "Braid Rug"
STRINGS.NAMES.RUG_BEARD = "Beard Rug"
STRINGS.NAMES.RUG_NAILBED = "Nailbed Rug"
STRINGS.NAMES.RUG_CRIME = "Crime Rug"
STRINGS.NAMES.RUG_TILES = "Soccer Rug"

STRINGS.NAMES.SHELVES_WOOD = "Carved Bookshelf"
STRINGS.NAMES.SHELVES_BASIC = "Basic Bookshelf"
STRINGS.NAMES.SHELVES_CINDERBLOCKS = "Cinderblock Bookshelf"
STRINGS.NAMES.SHELVES_MARBLE = "Marble Shelf"
STRINGS.NAMES.SHELVES_MIDCENTURY = "Windowed Cabinet"
STRINGS.NAMES.SHELVES_GLASS = "Glass Shelf"
STRINGS.NAMES.SHELVES_LADDER = "Ladder Shelf"
STRINGS.NAMES.SHELVES_HUTCH = "Hutch Shelf"
STRINGS.NAMES.SHELVES_INDUSTRIAL = "Industrial Shelf"
STRINGS.NAMES.SHELVES_ADJUSTABLE = "Adjustable Shelf"
STRINGS.NAMES.SHELVES_WALLMOUNT = "Wall Mounted Shelf"
STRINGS.NAMES.SHELVES_AFRAME = "A-Frame Shelf"
STRINGS.NAMES.SHELVES_CRATES = "Crates Shelf"
STRINGS.NAMES.SHELVES_FRIDGE = "Fridge"
STRINGS.NAMES.SHELVES_HOOKS = "Hook Shelf"
STRINGS.NAMES.SHELVES_FLOATING = "Floating Shelf"
STRINGS.NAMES.SHELVES_PIPE = "Pipe Shelf"
STRINGS.NAMES.SHELVES_HATTREE = "Hat Tree"
STRINGS.NAMES.SHELVES_PALLET = "Pallet Shelf"
STRINGS.NAMES.SHELVES_METAL = "Metal Shelf"

STRINGS.NAMES.SHELVES_DISPLAYCASE = "Display Case"

STRINGS.NAMES.JELLYBUG = "Bean Bugs"
STRINGS.NAMES.JELLYBUG_COOKED = "Cooked Bean Bugs"
STRINGS.NAMES.SLUGBUG = "Gummy Slug"
STRINGS.NAMES.SLUGBUG_COOKED = "Cooked Gummy Slug"
STRINGS.NAMES.ROCK_FLIPPABLE = "Stone Slab"

STRINGS.NAMES.PLAYERHOUSE_CITY = "Slanty Shanty"  
STRINGS.NAMES.PLAYERHOUSE_VILLA = "Glorious Villa"
STRINGS.NAMES.PLAYERHOUSE_COTTAGE = "Cozy Cottage"
STRINGS.NAMES.PLAYERHOUSE_MANOR = "Impressive Manor"
STRINGS.NAMES.PLAYERHOUSE_TUDOR = "Tudor Home"
STRINGS.NAMES.PLAYERHOUSE_GOTHIC = "Gothic Home"
STRINGS.NAMES.PLAYERHOUSE_BRICK = "Brick Home"
STRINGS.NAMES.PLAYERHOUSE_TURRET = "Turreted Home"

STRINGS.NAMES.PLAYER_HOUSE_COTTAGE_CRAFT = "Cottage Kit"
STRINGS.NAMES.PLAYER_HOUSE_VILLA_CRAFT = "Villa Kit"  
STRINGS.NAMES.PLAYER_HOUSE_TUDOR_CRAFT = "Tudor Home Kit"
STRINGS.NAMES.PLAYER_HOUSE_MANOR_CRAFT = "Manor Kit"
STRINGS.NAMES.PLAYER_HOUSE_GOTHIC_CRAFT = "Gothic Home Kit"
STRINGS.NAMES.PLAYER_HOUSE_BRICK_CRAFT = "Brick Home Kit"   
STRINGS.NAMES.PLAYER_HOUSE_TURRET_CRAFT = "Turreted Home Kit"   

STRINGS.NAMES.CLIPPINGS = "Clippings"

STRINGS.NAMES.BRAMBLESPIKE = "Brambles"

STRINGS.NAMES.CUTNETTLE = "Nettle"
STRINGS.NAMES.NETTLE = "Nettle Vine"
STRINGS.NAMES.DUG_NETTLE = "Nettle Plant"

STRINGS.NAMES.NETTLELOSANGE = "Nettle Rolls"

STRINGS.NAMES.DECO_RUINS_FOUNTAIN = "Wishing Well" 
STRINGS.NAMES.PUGALISK = "Pugalisk"       
STRINGS.NAMES.SNAKE_BONE = "Snake Bone"
STRINGS.NAMES.SNAKEBONESOUP = "Snake Bone Soup" 

STRINGS.NAMES.BANDITMAP = "Bandit Stash Map" 
STRINGS.NAMES.BANDITTREASURE = "Secret Bandit Camp" 

STRINGS.NAMES.BLUNDERBUSS = "Blunderbuss" 

STRINGS.NAMES.PUGALISK_FOUNTAIN = "Fountain of Youth"
STRINGS.NAMES.PUGALISK_RUINS_PILLAR = "Teetering Pillar"
STRINGS.NAMES.PUGALISK_TRAP_DOOR = "Ominous Carving" 

STRINGS.NAMES.TEA = "Tea"  
STRINGS.NAMES.ICEDTEA = "Iced Tea"
STRINGS.NAMES.TEATREE = "Tea Tree" 
STRINGS.NAMES.TEATREE_SAPLING = "Tea Tree Sapling"
STRINGS.NAMES.TEATREE_NUT = "Seed Pod"
STRINGS.NAMES.TEATREE_NUT_COOKED = "Cooked Seed Pod"

STRINGS.NAMES.WALL_PIG_RUINS = "Ancient Wall" 

STRINGS.NAMES.PIG_RUINS_DART_TRAP = "Striking Carving"
STRINGS.NAMES.PIG_RUINS_DART_STATUE = "Striking Statue"
STRINGS.NAMES.PIG_RUINS_SPEAR_TRAP = "Decorative Holes?" 
STRINGS.NAMES.PIG_RUINS_SPEAR_TRAP_TRIGGERED = "Nasty Spear Trap"
STRINGS.NAMES.PIG_RUINS_SPEAR_TRAP_BROKEN = "Busted Spear Trap" 
STRINGS.NAMES.PIG_RUINS_PRESSURE_PLATE = "Suspicious Stone"

STRINGS.NAMES.DISARMING_KIT = "Disarming Tools" 

STRINGS.NAMES.BALLPEIN_HAMMER = "Ball Pein Hammer" 

STRINGS.NAMES.GOLD_DUST = "Gold Dust"

STRINGS.NAMES.ALOE = "Aloe" 
STRINGS.NAMES.ALOE_COOKED = "Cooked Aloe" 
STRINGS.NAMES.ALOE_PLANTED = "Aloe"

STRINGS.NAMES.ASPARAGUS = "Asparagus"
STRINGS.NAMES.ASPARAGUS_COOKED = "Cooked Asparagus" 
STRINGS.NAMES.ASPARAGUS_PLANTED = "Asparagus"
STRINGS.NAMES.ASPARAGUSSOUP = "Asparagus Soup"
STRINGS.NAMES.SPICYVEGSTINGER = "Spicy Vegetable Stinger"
STRINGS.NAMES.FEIJOADA = "Feijoada"
STRINGS.NAMES.HARDSHELL_TACOS = "Hard Shell Tacos"
STRINGS.NAMES.GUMMY_CAKE = "Gummy Cake"
STRINGS.NAMES.STEAMEDHAMSANDWICH = "Steamed Ham Sandwich"

STRINGS.NAMES.RADISH = "Radish" 
STRINGS.NAMES.RADISH_COOKED = "Cooked Radish"
STRINGS.NAMES.RADISH_PLANTED = "Radish" 

STRINGS.NAMES.SNAKE_AMPHIBIOUS = "Viper" 

STRINGS.NAMES.SUNKEN_RELIC = "Sunken Object"  

STRINGS.NAMES.IRON = "Iron Ore" 

STRINGS.NAMES.CLAWPALMTREE = "Claw Palm Tree"       
STRINGS.NAMES.DUG_NETTLE = "Nettle Plant" 

STRINGS.NAMES.THUNDERBIRD = "Thunderbird" 
STRINGS.NAMES.THUNDERBIRDNEST = "Thundernest" 
STRINGS.NAMES.FEATHER_THUNDER = "Thunder Feather" 
STRINGS.NAMES.THUNDERHAT = "Thunderhat" 

STRINGS.NAMES.WEEVOLE = "Weevole" 
STRINGS.NAMES.WEEVOLE_CARAPACE = "Weevole Carapace" 
STRINGS.NAMES.ARMOR_WEEVOLE = "Weevole Mantle"

STRINGS.NAMES.TUBERTREE = "Tuber Tree" 
STRINGS.NAMES.CORK = "Cork" 

STRINGS.NAMES.CANDLEHAT = "Cork Candle Hat"
STRINGS.NAMES.CORK_BAT = "Cork Bat" 

STRINGS.NAMES.BAT_HIDE = "Pig Skin?"
STRINGS.NAMES.VAMPIRE_BAT_WING = "Batilisk Wing?"

STRINGS.NAMES.ANCIENT_ROBOT_RIBS = "Iron Hulk"
STRINGS.NAMES.ANCIENT_ROBOT_CLAW = "Iron Hulk" 
STRINGS.NAMES.ANCIENT_ROBOT_LEG = "Iron Hulk"
STRINGS.NAMES.ANCIENT_ROBOT_HEAD = "Iron Hulk" 
STRINGS.NAMES.ANCIENT_ROBOTS_ASSEMBLY = "Large Iron Hulk" 

STRINGS.NAMES.CLAWPALMTREE_SAPLING = "Claw Palm Sapling" 

STRINGS.NAMES.CORKBOAT = "Cork Bowl Canoe" 
STRINGS.NAMES.CORKCHEST = "Cork Barrel"

STRINGS.NAMES.BANDITHAT = "Swashy Hat" 
STRINGS.NAMES.PIGBANDIT = "Masked Pig" 

STRINGS.NAMES.PIG_RUINS_CREEPING_VINES = "Vines"

STRINGS.NAMES.SEDIMENTPUDDLE = "Sparkling Pool"
STRINGS.NAMES.GOLDPAN = "Gold Pan"

STRINGS.NAMES.PORKLAND_ENTRANCE = "Skyworthy"
STRINGS.NAMES.PORKLAND_EXIT = "Skyworthy"

STRINGS.NAMES.POG = "Pog" 

STRINGS.NAMES.PANGOLDEN = "Pangolden"

STRINGS.NAMES.ROC_LEG = "BFB"
STRINGS.NAMES.ROC_HEAD = "BFB"
STRINGS.NAMES.ROC_TAIL = "BFB"

STRINGS.NAMES.GNATMOUND = "Gnat Mound"
STRINGS.NAMES.GNAT = "Gnat Swarm"

STRINGS.NAMES.PORKLAND_INTRO = "Maxameleon"

STRINGS.NAMES.ROC_NEST_TREE1 = "Weathered Tree"
STRINGS.NAMES.ROC_NEST_TREE2 = "Weathered Tree"
STRINGS.NAMES.ROC_NEST_BUSH = "Weathered Shrub"
STRINGS.NAMES.ROC_NEST_BRANCH1 = "Weathered Branch"
STRINGS.NAMES.ROC_NEST_BRANCH2 = "Weathered Branch"
STRINGS.NAMES.ROC_NEST_TRUNK = "Weathered Trunk"
STRINGS.NAMES.ROC_NEST_HOUSE = "Weathered House"
STRINGS.NAMES.ROC_NEST_RUSTY_LAMP = "Rusty Lamp"


STRINGS.NAMES.ROC_NEST_DEBRIS1 = "Weathered Stick"
STRINGS.NAMES.ROC_NEST_DEBRIS2 = "Weathered Stick"
STRINGS.NAMES.ROC_NEST_DEBRIS3 = "Weathered Stick"
STRINGS.NAMES.ROC_NEST_DEBRIS4 = "Weathered Stick"

STRINGS.NAMES.ROC_NEST_EGG1 = "Petrified Egg"
STRINGS.NAMES.ROC_NEST_EGG2 = "Petrified Egg"
STRINGS.NAMES.ROC_NEST_EGG3 = "Petrified Egg"
STRINGS.NAMES.ROC_NEST_EGG4 = "Petrified Egg"

STRINGS.NAMES.ROC_ROBIN_EGG = "Stone Egg"

STRINGS.NAMES.TUBER_CROP = "Tuber"
STRINGS.NAMES.TUBER_BLOOM_CROP = "Blooming Tuber"
STRINGS.NAMES.TUBER_CROP_COOKED = "Fried Tuber"
STRINGS.NAMES.TUBER_BLOOM_CROP_COOKED = "Fried Blooming Tuber"

STRINGS.NAMES.ALLOY = "Alloy"

STRINGS.NAMES.ARMOR_METALPLATE = "Tin Suit"
STRINGS.NAMES.METALPLATEHAT = "Fancy Helmet"

STRINGS.NAMES.SMELTER = "Smelter"

STRINGS.NAMES.BUGREPELLENT = "Bug B'Gone"

STRINGS.NAMES.HOGUSPORKUSATOR = "Hogus Porkusator"

STRINGS.NAMES.GASCLOUD = "Noxious Cloud"

STRINGS.NAMES.WATERDROP = "Magic Water"

STRINGS.NAMES.LIFEPLANT = "Magic Flower"

STRINGS.NAMES.TRINKET_GIFTSHOP_1 = "Queen Malfalfa"
STRINGS.NAMES.TRINKET_GIFTSHOP_3 = "Post Card of the Royal Palace"
STRINGS.NAMES.TRINKET_GIFTSHOP_4 = "Can of Silly String"

STRINGS.NAMES.KEY_TO_CITY = "Key to the City"

STRINGS.NAMES.PEDESTAL_KEY = "Royal Gallery Key"

STRINGS.NAMES.ROYAL_GALLERY = "Royal Gallery Exhibit"

STRINGS.NAMES.APORKALYPSE_CLOCK = "Aporkalypse Calendar"
STRINGS.NAMES.ANCIENT_HERALD = "Ancient Herald"

STRINGS.NAMES.WALLCRACK_RUINS = "Suspicious Crack"

STRINGS.NAMES.DEFLATED_BALLOON = "Deflated Balloon"
STRINGS.NAMES.DEFLATED_BALLOON_BASKET = "Wicker Basket"

STRINGS.NAMES.SNAKE_FIRE = "Fire Snake"
STRINGS.NAMES.DISGUISEHAT = "Shamlet Mask"

STRINGS.NAMES.ALOE_SEEDS = "Aloe Seeds"
STRINGS.NAMES.ASPARAGUS_SEEDS = "Asparagus Seeds"
STRINGS.NAMES.RADISH_SEEDS = "Radish Seeds"

STRINGS.NAMES.ANCIENT_HERALD = "Ancient Herald"

STRINGS.NAMES.CAVE_EXIT_ROC = "Stone Plug"

STRINGS.NAMES.PORKLAND_INTRO_BASKET = "Wicker Basket"
STRINGS.NAMES.PORKLAND_INTRO_BALLOON = "Deflated Balloon"
STRINGS.NAMES.PORKLAND_INTRO_TRUNK = "Monogrammed Luggage"
STRINGS.NAMES.PORKLAND_INTRO_SUITCASE = "Monogrammed Luggage"
STRINGS.NAMES.PORKLAND_INTRO_FLAGS = "Useless Flags"
STRINGS.NAMES.PORKLAND_INTRO_SANDBAG = "Bag of Sand"

STRINGS.NAMES.TURF_BEARD_HAIR = "Beard Hair Rug" 

STRINGS.NAMES.HIPPO_ANTLER = "Hippopotamoose Antler"
STRINGS.NAMES.BILL_QUILL = "Platapine Quill"

STRINGS.NAMES.ANTLER = "Bird Whistle"
STRINGS.NAMES.PUGALISK_SKULL = "Pugalisk Skull"
STRINGS.NAMES.PUGALISK_CORPSE = "Petrifying Bones"

STRINGS.NAMES.BONESTAFF = "Pugalisk Wand"

STRINGS.NAMES.CITY_HAMMER = "Executive Hammer" 

STRINGS.NAMES.DECO_RUINS_ENDSWELL = "End's Well"     

STRINGS.NAMES.COMPOSTWRAP = "Compost Wrap"  	
STRINGS.NAMES.POISONBALM = "Poison Balm"
STRINGS.NAMES.ARMOR_BRAMBLE = "Bramble Husk"
STRINGS.NAMES.TRAP_BRAMBLE = "Bramble Trap"
STRINGS.NAMES.SILVERNECKLACE = "Silver Necklace"

STRINGS.NAMES.WEREWILBAFUR_HEAD = "Body Hair"
STRINGS.NAMES.WEREWILBAFUR_BODY = "Body Hair"
STRINGS.NAMES.WEREWILBAFUR_HANDS = "Body Hair"

STRINGS.NAMES.BRAMBLE_CORE = "Bramble Bloom"
STRINGS.NAMES.BRAMBLE_BULB = "Bramble Bulb"

STRINGS.NAMES.ROOTTRUNK_CHILD = "Root Trunk"

STRINGS.NAMES.ARMORVORTEXCLOAK = "Vortex Cloak"    
STRINGS.NAMES.ANCIENT_REMNANT = "Dark Tatters"    

STRINGS.NAMES.GOGGLESNORMALHAT = "Spectoggles"
STRINGS.NAMES.GOGGLESHEATHAT = "Infroggles"
STRINGS.NAMES.GOGGLESARMORHAT = "Visor"
STRINGS.NAMES.GOGGLESSHOOTHAT = "Fryfocals"     

STRINGS.NAMES.THUMPER = "Thumper"
STRINGS.NAMES.TELEBRELLA = "Telebrella"
STRINGS.NAMES.TELIPAD = "Telipad"
STRINGS.NAMES.ANCIENT_HULK = "Large Iron Hulk"

STRINGS.NAMES.ROCK_BASALT = "Basalt Eruption"

STRINGS.NAMES.TRUSTY_SHOOTER = "Pew-matic Horn"
STRINGS.NAMES.WHEELER_TRACKER = "Navigadget"

STRINGS.NAMES.LIVING_ARTIFACT = "Living Artifact"
STRINGS.NAMES.INFUSED_IRON = "Infused Iron"

STRINGS.NAMES.TELEPORTATO_HAMLET_RING = "Iron Thing"
STRINGS.NAMES.TELEPORTATO_HAMLET_BOX = "Rock Thing"
STRINGS.NAMES.TELEPORTATO_HAMLET_CRANK = "Lever Thing"
STRINGS.NAMES.TELEPORTATO_HAMLET_POTATO = "Relic Thing"
STRINGS.NAMES.TELEPORTATO_HAMLET_BASE = "Stone Thing"     

STRINGS.NAMES.HEDGE_BLOCK_ITEM = "Block Hedge" 
STRINGS.NAMES.HEDGE_BLOCK = "Hedge"

STRINGS.NAMES.HEDGE_CONE_ITEM = "Cone Hedge" 
STRINGS.NAMES.HEDGE_CONE = "Hedge"

STRINGS.NAMES.HEDGE_LAYERED_ITEM = "Layered Hedge" 
STRINGS.NAMES.HEDGE_LAYERED = "Hedge"

STRINGS.NAMES.LAWNORNAMENT_1 = "Layer Tree"
STRINGS.NAMES.LAWNORNAMENT_2 = "Irregular Tree"
STRINGS.NAMES.LAWNORNAMENT_3 = "Umbrella Tree"
STRINGS.NAMES.LAWNORNAMENT_4 = "Floopy Tree"
STRINGS.NAMES.LAWNORNAMENT_5 = "Funbrella Tree"
STRINGS.NAMES.LAWNORNAMENT_6 = "Flowering Tree"
STRINGS.NAMES.LAWNORNAMENT_7 = "Spiral Tree"

STRINGS.NAMES.GROUNDED_WILBA = "Wilba"

