-- local _GLOBAL = GLOBAL

-- _GLOBAL.setfenv(1, _GLOBAL)

-- local Vector3 = Vector3
-- local STRINGS = STRINGS

local FX =
{
    -- {
	    -- name = "sanity_raise",
	    -- bank = "blocker_sanity_fx",
	    -- build = "blocker_sanity_fx",
	    -- anim = "raise",
	    -- tintalpha = 0.5,
    -- },
    -- {
	    -- name = "sanity_lower",
	    -- bank = "blocker_sanity_fx",
	    -- build = "blocker_sanity_fx",
	    -- anim = "lower",
	    -- tintalpha = 0.5,
    -- },
    -- {
	    -- name = "die_fx",
	    -- bank = "die_fx",
	    -- build = "die",
	    -- anim = "small",
	    -- sound = "dontstarve/common/deathpoof",
	    -- -- tint = Vector3(90/255, 66/255, 41/255),
    -- },
    -- {
	    -- name = "sparks_fx",
	    -- bank = "sparks",
	    -- build = "sparks",
	    -- anim = {"sparks_1", "sparks_2", "sparks_3"},
    -- },
    -- -- {
	    -- -- name = "firework_fx",
	    -- -- bank = "firework",
	    -- -- build = "accomplishment_fireworks",
	    -- -- anim = "single_firework",
	    -- -- sound = "dontstarve/common/shrine/sadwork_fire",
	    -- -- sound2 = "dontstarve/common/shrine/sadwork_explo",
	    -- -- sounddelay2 = 26/30,
	    -- -- -- fn = function() GetClock():DoLightningLighting(.25) end,
	    -- -- -- fntime = 26/30
    -- -- },
    -- -- {
	    -- -- name = "multifirework_fx",
	    -- -- bank = "firework",
	    -- -- build = "accomplishment_fireworks",
	    -- -- anim = "multi_firework",
	    -- -- sound = "dontstarve/common/shrine/sadwork_fire",
	    -- -- sound2 = "dontstarve/common/shrine/firework_explo",
	    -- -- sounddelay2 = 26/30,
	    -- -- -- fn = function() GetClock():DoLightningLighting(1) end,
	    -- -- -- fntime = 26/30
    -- -- },
    -- {
	    -- name = "explode_small",
	    -- bank = "explode",
	    -- build = "explode",
	    -- anim = "small",
    -- },
    -- {
	    -- name = "explode_large",
	    -- bank = "explode",
	    -- build = "explode",
	    -- anim = "large",
    -- },
    -- {
	    -- name = "lightning_rod_fx",
	    -- bank = "lightning_rod_fx",
	    -- build = "lightning_rod_fx",
	    -- anim = "idle",
    -- },
    -- {
	    -- name = "splash",
	    -- bank = "splash",
	    -- build = "splash",
	    -- anim = "splash",
    -- },
    -- {
	    -- name = "small_puff",
	    -- bank = "small_puff",
	    -- build = "smoke_puff_small",
	    -- anim = "puff",
	    -- sound = "dontstarve/common/deathpoof",
    -- },
    -- {
	    -- name = "splash_ocean",
	    -- bank = "splash",
	    -- build = "splash_ocean",
	    -- anim = "idle",
    -- },
    -- {
	    -- name = "maxwell_smoke",
	    -- bank = "max_fx",
	    -- build = "max_fx",
	    -- anim = "anim",
    -- },
    -- {
	    -- name = "shovel_dirt",
	    -- bank = "shovel_dirt",
	    -- build = "shovel_dirt",
	    -- anim = "anim",
    -- },
    -- {
	    -- name = "mining_fx",
	    -- bank = "mining_fx",
	    -- build = "mining_fx",
	    -- anim = "anim",
    -- },
    -- {
	    -- name = "pine_needles",
	    -- bank = "pine_needles",
	    -- build = "pine_needles",
	    -- anim = "fall",
    -- },
    -- {
	    -- name = "pine_needles_chop",
	    -- bank = "pine_needles",
	    -- build = "pine_needles",
	    -- anim = "chop",
    -- },
    -- {
	    -- name = "green_leaves_chop",
	    -- bank = "tree_leaf_fx",
	    -- build = "tree_leaf_fx_green",
	    -- anim = "chop",
	    -- sound = "dontstarve_DLC001/fall/leaf_rustle",
	    -- dlc = true,
    -- },
    -- {
	    -- name = "red_leaves_chop",
	    -- bank = "tree_leaf_fx",
	    -- build = "tree_leaf_fx_red",
	    -- anim = "chop",
	    -- sound = "dontstarve_DLC001/fall/leaf_rustle",
	    -- dlc = true,
    -- },
    -- {
	    -- name = "orange_leaves_chop",
	    -- bank = "tree_leaf_fx",
	    -- build = "tree_leaf_fx_orange",
	    -- anim = "chop",
	    -- sound = "dontstarve_DLC001/fall/leaf_rustle",
	    -- dlc = true,
    -- },
    -- {
	    -- name = "yellow_leaves_chop",
	    -- bank = "tree_leaf_fx",
	    -- build = "tree_leaf_fx_yellow",
	    -- anim = "chop",
	    -- sound = "dontstarve_DLC001/fall/leaf_rustle",
	    -- dlc = true,
    -- },
    -- {
	    -- name = "purple_leaves_chop",
	    -- bank = "tree_monster_fx",
	    -- build = "tree_monster_fx",
    	-- anim = "chop",
	    -- sound = "dontstarve_DLC001/fall/leaf_rustle",
	    -- dlc = true,
    -- },
    -- {
	    -- name = "green_leaves",
	    -- bank = "tree_leaf_fx",
	    -- build = "tree_leaf_fx_green",
	    -- anim = "fall",
	    -- sound = "dontstarve_DLC001/fall/leaf_rustle",
	    -- dlc = true,
    -- },
    -- {
	    -- name = "red_leaves",
	    -- bank = "tree_leaf_fx",
	    -- build = "tree_leaf_fx_red",
	    -- anim = "fall",
	    -- sound = "dontstarve_DLC001/fall/leaf_rustle",
	    -- dlc = true,
    -- },
    -- {
	    -- name = "orange_leaves",
	    -- bank = "tree_leaf_fx",
	    -- build = "tree_leaf_fx_orange",
	    -- anim = "fall",
	    -- sound = "dontstarve_DLC001/fall/leaf_rustle",
	    -- dlc = true,
    -- },
    -- {
	    -- name = "yellow_leaves",
	    -- bank = "tree_leaf_fx",
	    -- build = "tree_leaf_fx_yellow",
    	-- anim = "fall",
	    -- sound = "dontstarve_DLC001/fall/leaf_rustle",
	    -- dlc = true,
    -- },
    -- {
	    -- name = "purple_leaves",
	    -- bank = "tree_monster_fx",
	    -- build = "tree_monster_fx",
    	-- anim = "fall",
	    -- sound = "dontstarve_DLC001/fall/leaf_rustle",
	    -- dlc = true,
    -- },
    -- {
	    -- name = "dr_warm_loop_1",
	    -- bank = "diviningrod_fx",
	    -- build = "diviningrod_fx",
	    -- anim = "warm_loop",
	    -- -- tint = Vector3(105/255, 160/255, 255/255),
    -- },
    -- {
	    -- name = "dr_warm_loop_2",
	    -- bank = "diviningrod_fx",
	    -- build = "diviningrod_fx",
	    -- anim = "warm_loop",
	    -- -- tint = Vector3(105/255, 182/255, 239/255),
    -- },
    -- {
	    -- name = "dr_warmer_loop",
	    -- bank = "diviningrod_fx",
	    -- build = "diviningrod_fx",
	    -- anim = "warmer_loop",
	    -- -- tint = Vector3(255/255, 163/255, 26/255),
    -- },
    -- {
	    -- name = "dr_hot_loop",
	    -- bank = "diviningrod_fx",
	    -- build = "diviningrod_fx",
	    -- anim = "hot_loop",
	    -- -- tint = Vector3(181/255, 32/255, 32/255),
    -- },
    -- {
	    -- name = "statue_transition",
	    -- bank = "statue_ruins_fx",
	    -- build = "statue_ruins_fx",
	    -- anim = "transform_nightmare",
	    -- tintalpha = 0.6,
    -- },
    -- {
	    -- name = "statue_transition_2",
	    -- bank = "die_fx",
	    -- build = "die",
	    -- anim = "small",
	    -- sound = "dontstarve/common/deathpoof",
	    -- -- tint = Vector3(0,0,0),
	    -- tintalpha = 0.6,
    -- },
    -- {
	    -- name = "sparklefx",
	    -- bank = "sparklefx",
	    -- build = "sparklefx",
	    -- anim = "sparkle",
	    -- sound = "dontstarve/common/chest_positive",
	    -- tintalpha = 0.6,
	    -- --transform = Vector3(1.5, 1, 1)
    -- },
    -- {
	    -- name = "book_fx",
	    -- bank = "book_fx",
	    -- build = "book_fx",
	    -- anim = "book_fx",
	    -- tintalpha = 0.4,
	    -- --transform = Vector3(1.5, 1, 1)
    -- },
    -- {
	    -- name = "waxwell_book_fx",
	    -- bank = "book_fx",
	    -- build = "book_fx",
	    -- anim = "book_fx",
	    -- -- tint =  Vector3(0,0,0),
	    -- --transform = Vector3(1.5, 1, 1) -- Commented out before in Hamlet
    -- },
    -- {
	    -- name = "chester_transform_fx",
	    -- bank = "die_fx",
	    -- build = "die",
	    -- anim = "small",
    -- },
    -- {
	    -- name = "wathgrithr_spirit",
	    -- bank = "wathgrithr_spirit",
	    -- build = "wathgrithr_spirit",
    	-- anim = "wathgrithr_spirit",
	    -- sound = "dontstarve_DLC001/characters/wathgrithr/valhalla",
	    -- sounddelay = .2,
	    -- dlc = true,
    -- },
    -- {
	    -- name = "groundpound_fx",
	    -- bank = "bearger_ground_fx",
	    -- build = "bearger_ground_fx",
	    -- sound = "dontstarve_DLC001/creatures/bearger/dustpoof",
    	-- anim = "idle",
	    -- dlc = true,
    -- },
    -- {
	    -- name = "groundpound_nosound_fx",
	    -- bank = "bearger_ground_fx",
	    -- build = "bearger_ground_fx",
    	-- anim = "idle",
	    -- dlc = true,
    -- },    
    -- {
	    -- name = "firesplash_fx",
	    -- bank = "dragonfly_ground_fx",
	    -- build = "dragonfly_ground_fx",
    	-- anim = "idle",
	    -- dlc = true,
	    -- bloom = true,
    -- },
    -- {
	    -- name = "tauntfire_fx",
	    -- bank = "dragonfly_fx",
	    -- build = "dragonfly_fx",
    	-- anim = "taunt",
	    -- dlc = true,
	    -- bloom = true,
    -- },
    -- {
	    -- name = "attackfire_fx",
	    -- bank = "dragonfly_fx",
	    -- build = "dragonfly_fx",
    	-- anim = "atk",
	    -- dlc = true,
	    -- bloom = true,
    -- },
    -- {
	    -- name = "vomitfire_fx",
	    -- bank = "dragonfly_fx",
	    -- build = "dragonfly_fx",
    	-- anim = "vomit",
    	-- twofaced = true,
	    -- dlc = true,
	    -- bloom = true,
    -- },
    -- {
    	-- name = "speech_fx",
    	-- bank = "twigs",
    	-- build = "twigs", 
    	-- anim = "idle",
    	-- dlc = true,
	-- },
    -- {
    	-- name = "splash_snow_fx",
    	-- bank = "splash",
    	-- build = "splash_snow",
    	-- anim = "idle",
    	-- dlc = true,
    -- },
    -- {
    	-- name = "mole_move_fx",
    	-- bank = "mole_fx",
    	-- build = "mole_move_fx",
    	-- anim = "move",
    	-- -- nameoverride = STRINGS.NAMES.MOLE_UNDERGROUND,
    	-- -- description = function(inst, viewer)
    					-- -- return GetString(viewer.prefab, "DESCRIBE", {"MOLE", "UNDERGROUND"})
    				-- -- end,
    	-- dlc = true,
	-- },
    -- {
	    -- name = "icespike_fx_1",
	    -- bank = "deerclops_icespike",
	    -- build = "deerclops_icespike",
	    -- anim = "spike1",
	    -- dlc = true,
	    -- sound = "dontstarve/creatures/deerclops/ice_small",

    -- },
    -- {
	    -- name = "icespike_fx_2",
	    -- bank = "deerclops_icespike",
	    -- build = "deerclops_icespike",
	    -- anim = "spike2",
	    -- sound = "dontstarve/creatures/deerclops/ice_small",
	    -- dlc = true,
    -- },
    -- {
	    -- name = "icespike_fx_3",
	    -- bank = "deerclops_icespike",
	    -- build = "deerclops_icespike",
	    -- anim = "spike3",
	    -- sound = "dontstarve/creatures/deerclops/ice_small",
	    -- dlc = true,
    -- },
    -- {
	    -- name = "icespike_fx_4",
	    -- bank = "deerclops_icespike",
	    -- build = "deerclops_icespike",
	    -- anim = "spike4",
	    -- sound = "dontstarve/creatures/deerclops/ice_small",
	    -- dlc = true,
    -- },
    -- {
    	-- name = "splash_water",
    	-- bank = "splash_water",
    	-- build = "splash_water",
    	-- anim = "idle",
    	-- dlc = true,
	-- },
    -- {
    	-- name = "splash_water_drop",
    	-- bank = "splash_water_drop",
    	-- build = "splash_water_drop",
    	-- anim = "idle",
    	-- dlc = true,
	-- },

	 -- {
    	-- name = "splash_water_sink",
    	-- bank = "splash_water_drop",
    	-- build = "splash_water_drop",
    	-- anim = "idle_sink",
    	-- dlc = true,
	-- },
	{
	    name = "hacking_fx",
	    bank = "hacking_fx",
	    build = "hacking_fx",
	    anim = "idle",
	    dlc = true,
    },
    -- {
	    -- name = "hacking_bamboo_fx",
	    -- bank = "hacking_bamboo_fx",
	    -- build = "hacking_bamboo_fx",
	    -- anim = "idle",
	    -- dlc = true,
    -- },
     -- {
    	-- name = "splash_water_big",
    	-- bank = "splash_water_big",
    	-- build = "splash_water_big",
    	-- anim = "idle",
    	-- dlc = true,
	-- },
	-- {
	    -- name = "boat_hit_fx", --dummy fx data, not working quite yet
	    -- bank = "boat_hit_debris",
	    -- build = "boat_hit_debris",
	    -- anim = "hit_rowboat",
    -- },
    -- {
    	-- name = "boat_hit_fx_raft_log",
	    -- bank = "boat_hit_debris",
	    -- build = "boat_hit_debris",
	    -- anim = "hit_raft_log",
    -- },
    -- {
    	-- name = "boat_hit_fx_raft_bamboo",
	    -- bank = "boat_hit_debris",
	    -- build = "boat_hit_debris",
	    -- anim = "hit_raft_bamboo",
    -- },
    -- {
    	-- name = "boat_hit_fx_rowboat",
	    -- bank = "boat_hit_debris",
	    -- build = "boat_hit_debris",
	    -- anim = "hit_rowboat",
    -- },
    -- {
    	-- name = "boat_hit_fx_cargoboat",
	    -- bank = "boat_hit_debris",
	    -- build = "boat_hit_debris",
	    -- anim = "hit_cargoboat",
    -- },
    -- {
    	-- name = "boat_hit_fx_armoured",
	    -- bank = "boat_hit_debris",
	    -- build = "boat_hit_debris",
	    -- anim = "hit_armoured",
    -- },
    -- {
    	-- name = "boat_hit_fx_corkboat",
	    -- bank = "boat_hit_debris",
	    -- build = "boat_hit_debris",
	    -- anim = "hit_corkboat",
    -- },    
    -- {
    	-- name = "boat_hit_fx_quackeringram",
	    -- bank = "boat_hit_debris",
	    -- build = "boat_hit_debris",
	    -- anim = "hit_raft_quackeringram",
        -- dlc = true
    -- },    
    -- {
    	-- name = "splash_footstep",
    	-- bank = "splash_footstep",
    	-- build = "splash_footstep",
    	-- anim = "anim",
    	-- dlc = true,
	-- },
    -- {
    	-- name = "jungle_chop",
    	-- bank = "chop_jungle",
    	-- build = "chop_jungle",
    	-- anim = "chop",
    	-- dlc = true,
	-- },
    -- {
    	-- name = "jungle_fall",
    	-- bank = "chop_jungle",
    	-- build = "chop_jungle",
    	-- anim = "fall",
    	-- dlc = true,
	-- },
    -- {
    	-- name = "mangrove_chop",
    	-- bank = "chop_mangrove",
    	-- build = "chop_mangrove",
    	-- anim = "chop",
    	-- dlc = true,
	-- },
    -- {
    	-- name = "mangrove_fall",
    	-- bank = "chop_mangrove",
    	-- build = "chop_mangrove",
    	-- anim = "fall",
    	-- dlc = true,
	-- },
	-- {
		-- name = "bombsplash",
    	-- bank = "bombsplash",
    	-- build = "water_bombsplash",
    	-- anim = "splash",
    	-- dlc = true,
	-- },
	-- {
		-- name = "lava_bombsplash",
    	-- bank = "lava_bombsplash",
    	-- build = "lava_bombsplash",
    	-- anim = "splash",
    	-- dlc = true,
	-- },
	-- {
		-- name = "clouds_bombsplash",
    	-- bank = "clouds_bombsplash",
    	-- build = "clouds_bombsplash",
    	-- anim = "splash",
    	-- dlc = true,
	-- },
	-- {
		-- name = "pixel_out",
    	-- bank = "pixels",
    	-- build = "pixel_fx",
    	-- anim = "out",
    	-- dlc = true,
	-- },
	-- {
		-- name = "pixel_in",
    	-- bank = "pixels",
    	-- build = "pixel_fx",
    	-- anim = "in",
    	-- dlc = true,
	-- },
    -- {
	    -- name = "small_puff_light",
	    -- bank = "small_puff",
	    -- build = "smoke_puff_small",
	    -- anim = "puff",
	    -- sound = "dontstarve/common/deathpoof",
	    -- tintalpha = 0.5,
    -- },
    -- {
	    -- name = "coconut_chunks",
	    -- bank = "ground_breaking",
	    -- build = "ground_chunks_breaking",
	    -- anim = "idle",
	    -- sound = "dontstarve_DLC002/creatures/palm_tree_guard/coconut_explode",
	    -- -- tint = Vector3(183/255,143/255,85/255),
	-- },
	-- {
	    -- name = "poop_splat",
	    -- bank = "ground_breaking",
	    -- build = "ground_chunks_breaking",
	    -- anim = "idle",
	    -- sound = "dontstarve_DLC002/common/poop_splat",
	    -- -- tint = Vector3(183/255,143/255,85/255),
	-- },
	-- {
	    -- name = "smoke_out",
	    -- bank = "smoke_out",
	    -- build = "smoke_plants",
	    -- anim = "smoke_loop",
	    -- --sound = "dontstarve/common/deathpoof",
	    -- --tintalpha = 0.5,
    -- },
    -- {
	    -- name = "shock_machines_fx",
	    -- bank = "shock_machines_fx",
	    -- build = "shock_machines_fx",
	    -- anim = "shock",
	    -- --sound = "dontstarve_DLC002/creatures/palm_tree_guard/coconut_explode",

	-- },
	-- {
		-- name = "feathers_packim_fire",
	    -- bank = "feathers_packim",
	    -- build = "feathers_packim_fire",
	    -- anim = "transform",
	-- },
	-- {
		-- name = "feathers_packim_fat",
	    -- bank = "feathers_packim",
	    -- build = "feathers_packim",
	    -- anim = "transform",
	-- },
	-- {
		-- name = "feathers_packim",
	    -- bank = "feathers_packim",
	    -- build = "feathers_packim",
	    -- anim = "transform",
	-- },
    -- {
	    -- name = "boat_death",
	    -- bank = "boatdeathshadow",
	    -- build = "boat_death_shadows",
	    -- anim = "boat_death",
	    -- tintalpha = 0.5,
    -- },
    -- {
    	-- name = "dragoon_charge_fx",
    	-- bank = "fx",
    	-- build = "dragoon_charge_fx",
    	-- anim = "move",
	-- },
    -- {
    	-- name = "splash_lava_drop",
    	-- bank = "splash_lava_drop",
    	-- build = "splash_lava_drop",
    	-- anim = "idle_sink",
    	-- dlc = true,
	-- },
    -- {
    	-- name = "splash_clouds_drop",
    	-- bank = "splash_clouds_drop",
    	-- build = "splash_clouds_drop",
    	-- anim = "idle_sink",
    	-- dlc = true,
	-- },
    -- {
    	-- name = "kraken_ink_splat",
    	-- bank = "ink",
    	-- build = "ink_projectile",
    	-- anim = "splat",
    	-- dlc = true,
	-- },
    -- {
    	-- name = "mangrove_chop",
    	-- bank = "chop_mangrove",
    	-- build = "chop_mangrove",
    	-- anim = "chop",
    	-- dlc = true,
	-- },	
    -- {
    	-- name = "chop_mangrove_pink",
    	-- bank = "chop_mangrove",
    	-- build = "chop_mangrove_pink",
    	-- anim = "chop",
    	-- dlc = true,
	-- },	
    -- {
    	-- name = "fall_mangrove_pink",
    	-- bank = "chop_mangrove",
    	-- build = "chop_mangrove_pink",
    	-- anim = "fall",
    	-- dlc = true,
	-- },	

    -- {
    	-- name = "chop_mangrove_blue",
    	-- bank = "chop_mangrove",
    	-- build = "chop_mangrove_blue",
    	-- anim = "chop",
    	-- dlc = true,
	-- },	
    -- {
    	-- name = "fall_mangrove_blue",
    	-- bank = "chop_mangrove",
    	-- build = "chop_mangrove_blue",
    	-- anim = "fall",
    	-- dlc = true,
	-- },	

	{
	    name = "hacking_tall_grass_fx", 
	    bank = "hacking_fx", 
	    build = "hacking_tall_grass_fx", 
	    anim = "idle",
	    -- dlc = true,
    },	
	{
		name = "circle_puff_fx",
    	bank = "circle_puff_fx",
    	build = "circle_puff_fx",
    	anim = "idle",
    	-- dlc = true,
	},    
    {
    	name = "snake_scales_fx",
    	bank = "snake_scales_fx",
    	build = "snake_scales_fx",
    	anim = "idle",
    	-- dlc = true,
	},
	{
    	name = "int_ceiling_dust_fx",
    	bank = "int_ceiling_dust_fx",
    	build = "int_ceiling_dust_fx",
    	anim = "idle",
    	-- dlc = true,
	},
	{
    	name = "robot_leaf_fx",
    	bank = "robot_leaf_fx",
    	build = "robot_leaf_fx",
    	anim = "idle",
    	-- dlc = true,
	},
	{
    	name = "sparks_green_fx",
    	bank = "sparks",
    	build = "sparks_green",
	    -- anim = {"sparks_1", "sparks_2", "sparks_3"}, -- Seems it needs to support a table of animations to properly reflect Hamlet again. Or I could separate them out into 3?
	    anim = "sparks_1",
    	-- dlc = true,
	},	
    {
        name = "spat_splat_fx",
        bank = "spat_splat",
        build = "spat_splat",
        anim = "idle",
        -- dlc = true,
    },	
    {
        name = "spat_splash_fx_full",
        bank = "spat_splash",
        build = "spat_splash",
        anim = "full",
        -- dlc = true,        
    },
    {
        name = "spat_splash_fx_med",
        bank = "spat_splash",
        build = "spat_splash",
        anim = "med",
        -- dlc = true,        
    },
    {
        name = "spat_splash_fx_low",
        bank = "spat_splash",
        build = "spat_splash",
        anim = "low",
        -- dlc = true,        
    },
    {
        name = "spat_splash_fx_melted", 
        bank = "spat_splash", 
        build = "spat_splash", 
        anim = "melted",
        -- dlc = true,        
    },    
    -- {
        -- name = "beefalo_transform_fx",
        -- bank = "beefalo_fx",
        -- build = "beefalo_fx",
        -- anim = "transform",
        -- --#TODO: this one
        -- sound = "dontstarve/ghost/ghost_haunt",
    -- },    
    -- {
        -- name = "bramblefx", 
        -- bank = "bramblefx", 
        -- build = "bramblefx", 
        -- anim = "idle",
        -- dlc = true,        
    -- },
    -- {
        -- name = "rock_hit_debris", 
        -- bank = "rock_hit_debris", 
        -- build = "rock_hit_debris", 
        -- anim = "hit_rock_ruins",
        -- dlc = true,        
    -- },
    -- {
        -- name = "vortex_cloak_fx", 
        -- bank = "vortex_cloak_fx", 
        -- build = "vortex_cloak_fx", 
        -- anim = "idle",
        -- dlc = true,        
    -- },
    {
        name = "metal_hulk_ring_fx", 
        bank = "metal_hulk_ring_fx", 
        build = "metal_hulk_ring_fx", 
        anim = "idle",
        -- dlc = true,        
    },
    {
	    name = "groundpound_fx_hulk",
	    bank = "bearger_ground_fx",
	    build = "bearger_ground_fx",
	    sound = "dontstarve_DLC003/creatures/boss/hulk_metal_robot/dust",
    	anim = "idle",
	    -- dlc = true,
    },    
    {
        name = "laser_burst_fx", 
        bank = "laser_ring_fx", 
        build = "laser_ring_fx", 
        anim = "idle",
        -- dlc = true,        
    },    
    {
        name = "living_suit_explode_fx", 
        bank = "living_suit_explode_fx", 
        build = "living_suit_explode_fx", 
        anim = "idle",
        -- dlc = true,        
    },        
}

return FX
