return {
-- INTERIOR ROOM SIZES
	ROOM_TINY_WIDTH   = 15,
	ROOM_TINY_DEPTH   = 10,
	
	ROOM_SMALL_WIDTH  = 18,
 	ROOM_SMALL_DEPTH  = 12,

 	ROOM_MEDIUM_WIDTH = 24,
 	ROOM_MEDIUM_DEPTH = 16,

 	ROOM_LARGE_WIDTH  = 26,
 	ROOM_LARGE_DEPTH  = 18,


 	SCORPION_HEALTH = 200,
 	SCORPION_DAMAGE = 20,
 	SCORPION_ATTACK_PERIOD = 3,
 	SCORPION_TARGET_DIST = 4,
 	SCORPION_INVESTIGATETARGET_DIST = 6,
 	SCORPION_WAKE_RADIUS = 4,
 	SCORPION_FLAMMABILITY = .33,
 	SCORPION_SUMMON_WARRIORS_RADIUS = 12,
 	SCORPION_EAT_DELAY = 1.5,
 	SCORPION_ATTACK_RANGE = 3,		
 	SCORPION_STING_RANGE = 2,		

 	SCORPION_WALK_SPEED = 3,
 	SCORPION_RUN_SPEED = 5,

 	SPEAR_TRAP_HEALTH = 100,
 	SPEAR_TRAP_DAMAGE = TUNING.BASE_SURVIVOR_ATTACK,

 	SNAKE_SPEED = 3,
 	SNAKE_TARGET_DIST = 8,
 	SNAKE_KEEP_TARGET_DIST= 15,
 	SNAKE_HEALTH = 100,
 	SNAKE_DAMAGE = 10,
 	SNAKE_ATTACK_PERIOD = 3,
 	SNAKE_POISON_CHANCE = 0.25,
 	SNAKE_POISON_START_DAY = 3, -- the day that poison TUNING.SNAKEs have a chance to show up
 	SNAKEDEN_REGEN_TIME = 3,--*TUNING.SEG_TIME
 	SNAKEDEN_RELEASE_TIME = 5,
 	SNAKE_JUNGLETREE_CHANCE = 0.5, -- chance of a normal TUNING.SNAKE
 	SNAKE_JUNGLETREE_POISON_CHANCE = 0.25, -- chance of a poison TUNING.SNAKE
 	SNAKE_JUNGLETREE_AMOUNT_TALL = 2, -- num of times to try and spawn a TUNING.SNAKE from a tall tree
 	SNAKE_JUNGLETREE_AMOUNT_MED = 1, -- num of times to try and spawn a TUNING.SNAKE from a normal tree
 	SNAKE_JUNGLETREE_AMOUNT_SMALL = 1, -- num of times to try and spawn a TUNING.SNAKE from a small tree
 	SNAKEDEN_MAX_SNAKES = 3,
 	SNAKEDEN_CHECK_DIST = 20,
 	SNAKEDEN_TRAP_DIST = 2,

 	DECO_RUINS_BEAM_WORK = 6,

 	PIG_RUINS_DART_DAMAGE = TUNING.BASE_SURVIVOR_ATTACK, --wilson_attack
 	ROCKS_MINE_GIANT = 10,

 	MAGNIFYING_GLASS_DAMAGE = TUNING.BASE_SURVIVOR_ATTACK *.125,
 	CORK_BAT_DAMAGE = TUNING.BASE_SURVIVOR_ATTACK * 1.5,
 	BRUSH_DAMAGE = TUNING.BASE_SURVIVOR_ATTACK*.8,
	    
 	TRUSTY_SHOOTER_DAMAGE_HIGH = 60,
 	TRUSTY_SHOOTER_DAMAGE_MEDIUM = 45,
 	TRUSTY_SHOOTER_DAMAGE_LOW = TUNING.BASE_SURVIVOR_ATTACK,

 	TRUSTY_SHOOTER_ATTACK_RANGE_HIGH = 11,
 	TRUSTY_SHOOTER_ATTACK_RANGE_MEDIUM = 9,
 	TRUSTY_SHOOTER_ATTACK_RANGE_LOW = 7,

 	TRUSTY_SHOOTER_HIT_RANGE_HIGH = 13,
 	TRUSTY_SHOOTER_HIT_RANGE_MEDIUM = 11,
 	TRUSTY_SHOOTER_HIT_RANGE_LOW = 9,

 	TRUSTY_SHOOTER_TIERS = {
		AMMO_HIGH = {
			"gears",
			"purplegem",
			"bluegem",
			"redgem",
			"orangegem",
			"yellowgem",
			"greengem",
			"oinc10",
			"oinc100",
			"nightmarefuel",
			"gunpowder",
			"relic_1",
			"relic_2",
			"relic_3",
			"relic_4",
			"relic_5",
		},

		AMMO_LOW = 
		{
			"feather_crow",
			"feather_robin",
			"feather_robin_winter",
			"feather_thunder",
			"ash",
			"beardhair",
			"beefalowool",
			"butterflywings",
			"clippings",
			"cutgrass",
			"cutreeds",
			"foliage",
			"palmleaf",
			"papyrus",
			"petals",
			"petals_evil",
			"pigskin",
			"silk",
			"seaweed",
		}
	},

 	LITTLE_HAMMER_DAMAGE = TUNING.BASE_SURVIVOR_ATTACK*0.3,
 	LITTLE_HAMMER_USES = 10,
 	SHEARS_DAMAGE = TUNING.BASE_SURVIVOR_ATTACK * .5,
 	SHEARS_USES = 20,

 	MAGNIFYING_GLASS_USES = 10,
		
 	RUINS_BAT_SPEED_MULT = 0.1,

 	TORCH_ATTACK_IGNITE_PERCENT = 1,

 	SPRING_COMBAT_MOD = 1.33,

 	PIG_DAMAGE = 33,
 	PIG_HEALTH = 250,
 	PIG_ATTACK_PERIOD = 3,
 	PIG_TARGET_DIST = 16,
 	PIG_LOYALTY_MAXTIME = 2.5*TUNING.TOTAL_DAY_TIME,
 	PIG_LOYALTY_PER_HUNGER = TUNING.TOTAL_DAY_TIME/25,
 	PIG_MIN_POOP_PERIOD = TUNING.SEG_TIME * .5,

 	SPIDER_LOYALTY_MAXTIME = 2.5*TUNING.TOTAL_DAY_TIME,
 	SPIDER_LOYALTY_PER_HUNGER = TUNING.TOTAL_DAY_TIME/25,

 	WEREPIG_DAMAGE = 40,
 	WEREPIG_HEALTH = 350,
 	WEREPIG_ATTACK_PERIOD = 2,

 	PIG_GUARD_DAMAGE = 33,
 	PIG_GUARD_HEALTH = 300,
 	PIG_GUARD_ATTACK_PERIOD = 1.5,
 	PIG_GUARD_TARGET_DIST = 8,
 	PIG_GUARD_DEFEND_DIST = 20, 

 	PIG_BANDIT_DAMAGE = 33,
 	PIG_BANDIT_HEALTH = 250,
 	PIG_BANDIT_ATTACK_PERIOD = 3,
 	PIG_BANDIT_TARGET_DIST = 16,
 	PIG_BANDIT_LOYALTY_MAXTIME = 2.5*TUNING.TOTAL_DAY_TIME,
 	PIG_BANDIT_LOYALTY_PER_HUNGER = TUNING.TOTAL_DAY_TIME/25,
 	PIG_BANDIT_MIN_POOP_PERIOD = TUNING.SEG_TIME * .5,
 	PIG_BANDIT_TARGET_DIST = 16,

 	CITY_PIG_GUARD_TARGET_DIST = 20,

 	PIG_RUN_SPEED = 5,
 	PIG_WALK_SPEED = 3,

 	WEREPIG_RUN_SPEED = 7,
 	WEREPIG_WALK_SPEED = 3,

 	PIG_BANDIT_RUN_SPEED = 7,
 	PIG_BANDIT_WALK_SPEED = 3,

 	ROBOT_TARGET_DIST = 15,
 	ROBOT_RIBS_DAMAGE = TUNING.BASE_SURVIVOR_ATTACK,
 	ROBOT_RIBS_HEALTH = 1000,
 	ROBOT_LEG_DAMAGE = TUNING.BASE_SURVIVOR_ATTACK*2,
		
 	LASER_DAMAGE = 20,

 	ANCIENT_HULK_DAMAGE = 200,
 	ANCIENT_HULK_MINE_DAMAGE = 100,
 	ANCIENT_HULK_MELEE_RANGE = 5.5,
 	ANCIENT_HULK_ATTACK_RANGE = 5.5,

 	IRON_LORD_DAMAGE = TUNING.BASE_SURVIVOR_ATTACK*2,
 	IRON_LORD_TIME = 3*60,

 	INFUSED_IRON_PERISHTIME = TUNING.TOTAL_DAY_TIME*2,

 	RUINS_ENTRANCE_VINES_HACKS = 4,
 	RUINS_DOOR_VINES_HACKS = 2,
}
