local ToLoad = {
	Prefabs = {
		"playerhouse_city",
		"pighousewithinterior",
		"generic_door",
		"home_prototyper",
		"generic_wall_back",
		"generic_wall_side",
		"prop_door",
		"generic_interior",
		"deco_roomglow",
		"shelf",
		"shelf_slot",
		"deco_antiquities",
		"deco_swinging_light",
		"deco_placers",
		"deco",
		"deco_lightglow",
		"deco_academy",
		"deco_chair",
		"deco_florist",
		"deco_lamp",
		"deco_plantholder",
		"deco_ruins_fountain",
		"deco_table",
		"deco_wall_ornament",
		"construction_permit",
		"house_door",
		"oincs", 
		"vampirebatcave",
		"pig_ruins_entrance",
		"pig_ruins_creeping_vines",
		"pig_ruins_dart",
		"pig_ruins_dart_statue",
		"pig_ruins_light_beam",
		"pig_ruins_pressure_plate",
		"pig_ruins_spear_trap",
		"pig_ruins_torch",
		"scorpion",
		"deep_jungle_fern_noise",
		"rocks_ham",
		"snake",
		"smashingpot", -- This darn thing is instantly crashing the entire game, and I want to know why
		"ham_light_rays",
		"wallcrack_ruins",
		"relics",
		"ham_fx",
		"cave_entrance_roc",
		"pigman_city",
		"pig_shop",
		"musac",
		"shop_pedestals",
		"shop_spawner",
		"shop_trinket",
		"pigman_shopkeeper_desk",
		"rug",
		"littlehammer",
		"iron",
		"ancient_robots",
		"ancient_robots_assembly",
		"laser",
		"laser_ring",
		"living_artifact",
		"waterbot",
		"waterbot_none",
		"ancient_hulk",
		"interior_wall_fx",
		"deed",
		"demolition_permit",
		"securitycontract",
		"interior_collision",
		"chitin",
		"city_lamp",
		"pighouse_city",
		"alloy",
		"smelter",
		"reconstruction_project",
		"waterdrop",
		"floweroflife"
	},
	
	Assets = {
		Asset("IMAGE", "images/colour_cubes/pigshop_interior_cc.tex"),
	
		Asset("IMAGE", "images/inventoryimages.tex"),
		Asset("ATLAS", "images/inventoryimages.xml"),
		
		Asset("IMAGE", "images/inventoryimages_2.tex"),
		Asset("ATLAS", "images/inventoryimages_2.xml"),
		
		Asset("IMAGE", "images/minimap/ham_minimap_atlas.tex"),
		Asset("ATLAS", "images/minimap/ham_minimap_data.xml"),
		
		Asset("SOUNDPACKAGE", "sound/dontstarve_DLC003.fev"),
		Asset("SOUND", "sound/DLC003_sfx.fsb"),
		
		Asset("ANIM", "anim/player_actions_tap.zip"),
		
		Asset("ANIM", "anim/player_living_suit_destruct.zip"),
		Asset("ANIM", "anim/player_living_suit_morph.zip"),
		Asset("ANIM", "anim/player_living_suit_punch.zip"),
		Asset("ANIM", "anim/player_living_suit_shoot.zip"),
		
		Asset("ANIM", "anim/living_suit_build.zip"),
		Asset("ANIM", "anim/living_suit_explode_fx.zip"),
		Asset("ANIM", "anim/livingartifact_meter.zip"),
		
		Asset("ANIM", "anim/player_lifeplant.zip"), -- Will either of these work?
		Asset("ANIM", "anim/player_rebirth.zip"),
		
		Asset("IMAGE", "levels/textures/interiors/pig_ruins_panel.tex"),
		Asset("IMAGE", "levels/textures/interiors/ground_ruins_slab.tex"),
		Asset("IMAGE", "levels/textures/interiors/pig_ruins_panel_blue.tex"),
		Asset("IMAGE", "levels/textures/interiors/ground_ruins_slab_blue.tex"),
		Asset("IMAGE", "levels/textures/interiors/batcave_wall_rock.tex"),
		Asset("IMAGE", "levels/textures/interiors/batcave_floor.tex"),
		Asset("IMAGE", "levels/textures/noise_woodfloor.tex"),
		Asset("IMAGE", "levels/textures/interiors/harlequin_panel.tex"),
		Asset("IMAGE", "levels/textures/interiors/shop_wall_woodwall.tex"),
		Asset("IMAGE", "levels/textures/interiors/shop_floor_hexagon.tex"),
		Asset("IMAGE", "levels/textures/interiors/shop_wall_circles.tex"),
		Asset("IMAGE", "levels/textures/interiors/shop_floor_sheetmetal.tex"),
		Asset("IMAGE", "levels/textures/interiors/shop_wall_checkered_metal.tex"),
		Asset("IMAGE", "levels/textures/interiors/shop_floor_checker.tex"),
		Asset("IMAGE", "levels/textures/interiors/shop_floor_hoof_curvy.tex"),
		Asset("IMAGE", "levels/textures/interiors/shop_wall_fullwall_moulding.tex"),
		Asset("IMAGE", "levels/textures/interiors/shop_wall_sunflower2.tex"),
		Asset("IMAGE", "levels/textures/interiors/floor_cityhall.tex"),
		Asset("IMAGE", "levels/textures/interiors/wall_mayorsoffice_whispy.tex"),
		Asset("IMAGE", "levels/textures/interiors/shop_wall_marble.tex"),
	},

	MiniMapAtlases = {
		"images/minimap/ham_minimap_data.xml",
	},

	InventoryItemsAtlasses = {
		{
			atlas = resolvefilepath("images/inventoryimages.xml"),
			texture = require("assets/inventorytextures1"),
		},
		{
			atlas = resolvefilepath("images/inventoryimages_2.xml"),
			texture = require("assets/inventorytextures2"),
		}
	},
}

return ToLoad